### ISSUE TITLE
名前の表示のデザイン改善

### ISSUE THREAD

**Issue by hilohiro** [rubyist-connect/rubyist-connect#1]

**Comment by yuji-shimoda** [comment]
ユーザ一覧を表示した際、名前やニックネームは画像の吹き出しとして表示させたい。
http://iamceege.github.io/tooltipster/

**Comment by JunichiIto** [comment]
スペースも空けた方がいいのでは

**Comment by yuji-shimoda** [comment]
この件、懇親会で maki さんに否定されました。＃現状の表示された状態の方が良いとのこと
スペースも以前より空いており見やすくなっていると思うのでクローズしたいと思います。
