### ISSUE TITLE
HTML5のinput[type=date]がIEなどで非対応

### ISSUE THREAD

**Issue by izumin5210** [rubyist-connect/rubyist-connect#101]
[`ActionView::Helpers::FormHelper#date_field`](http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-date_field)だと哀しいブラウザがある

参考: [HTML5で追加されたinput typeのブラウザ対応について検証してみた。 | 株式会社LIG](http://liginc.co.jp/web/html-css/html/42756)

**Comment by izumin5210** [comment]
#89
#98

**Comment by izumin5210** [comment]
jQuery UIの[Datepicker](http://jqueryui.com/datepicker/)という手もあるが，年を遡るのがしんどい
（HTML5のdate pickerなら数字で入力可）

**Comment by JunichiIto** [comment]
普通のテキストボックスとして入力すれば一応機能するので、いったん対応不要とします。
