### ISSUE TITLE
トップページ用テキスト原稿を作る

### ISSUE THREAD

**Issue by kanizmb** [rubyist-connect/rubyist-connect#107]
@yuji-shimoda 
https://dl.dropboxusercontent.com/u/350306729/rubyistconnect_fonts.html
- [ ] キャッチコピー
- [ ] サービス概要テキスト
- [ ] about 用見出し3件

の作成をお願いします。
必要に応じて構成や文字分量の変更も可能です。

**Comment by yuji-shimoda** [comment]
# キャッチフレーズ（案）
- Ruby の世界は、まだまだ広い
- Rubyist とツナガル
- Rubyist は、すぐそこに
- 繋がろう Rubyist
- Hello Ruby World

# サービス概要テキスト
- Rubyist Connect は、Rubyist と Rubyist を繋げることで
  Rubyist をサポートします。

# About の見出し３つ

## Share
- 近くの Rubyist と

## Search
- 趣味の近い Rubyist を

## Education
- 勉強会をサポート

**Comment by yuji-shimoda** [comment]
# サービス概要テキスト
- Rubyist Connect は、あなたの身近な Rubyist や趣味の近い Rubyist を探すことができます。
  そして、魅力的な Rubyist とつながって一緒に勉強してみませんか。

**Comment by kanizmb** [comment]
ありがとうございました。
反映してプルリク出しました。
