### ISSUE TITLE
ユーザ一覧は3カラムにする

### ISSUE THREAD

**Issue by yamasy1549** [rubyist-connect/rubyist-connect#118]
makiさんの参考に
![c664f4ee-98cc-11e4-99d7-d6749470d303](https://cloud.githubusercontent.com/assets/7820884/5690881/090d1b7c-98ec-11e4-9e4d-cf1d22544463.png)

**Comment by JunichiIto** [comment]
ユーザー一覧については僕もここでissueを挙げました。

https://github.com/yuji-shimoda/rubyist-connect/issues/148

どうするのがいいのかな～？？

**Comment by kanizmb** [comment]
#148 に統合のためclose
