### ISSUE TITLE
Eventの登録時に楽観ロックの制御が必要じゃない？

### ISSUE THREAD

**Issue by Koichi-Kobayashi** [rubyist-connect/rubyist-connect#123]
現状、Eventは誰でも登録出来て後勝ちになっている。

Rails4で楽観的ロックを実装する
http://ruby-rails.hatenadiary.com/entry/20141209/1418123425

**Comment by JunichiIto** [comment]
> Eventの登録時に楽観ロックの制御

これはね〜、僕も業務系SEをやってる頃は結構気にしてたけど、web系がメインになってからはほとんど聞かなくなりましたね。

後勝ちで更新されると誰かのお金が失われるとか、やたら頻繁に更新が衝突するとか、そういう深刻なレベルであれば考慮が必要ですが、そうでなければ「最悪、後勝ちでもいいんじゃね？」という雰囲気です。

参考までに、GitHubのWikiページの動きを確認してみましたが、楽観的ロックは働いておらず、後勝ちになりました。

というわけで、いったんクローズさせてもらいますね。

「楽観的ロックを付けないとこんな深刻な問題が！！」というのが発覚した時にまた議論させてください。

**Comment by springaki** [comment]
@JunichiIto  内容については +1 ですー

> というわけで、いったんクローズさせてもらいますね。

相手の同意を得てから closeすると更によいかもー :cherry_blossom: 
あんまりにも反応なかったりすれば様子見て Collaborator陣で closeしましょー。

**Comment by JunichiIto** [comment]
> 相手の同意を得てから closeすると更によいかもー 

これはねー、僕も半分agreeなんですが、そうすると「このissueはあとでクローズしなきゃ」というタスクが増えるので、避けたいなーと思っています。

issueの件数が少ないときはいいんですが、今は結構数があるので極力少なくしたいなという思いがありまして。

GitHub issueはいつでもreopenしたり、コメントを追加したりできるので、close後も議論はできるのかなーと思っています。

というわけで僕は積極的なcloseに一票です。
