### ISSUE TITLE
GitHubニックネームと他のニックネームが異なる場合GitHubニックネームで検索できない

### ISSUE THREAD

**Issue by t-oginogin** [rubyist-connect/rubyist-connect#126]
t_oginoginだと見つかるけど、t-oginoginだと見つからない

**Comment by t-oginogin** [comment]
GitHubのニックネームはt-oginoginと思っていたら、ニックネームではないとのこと。

**Comment by t-oginogin** [comment]
GitHubはニックネームではなくアカウントで検索できるとうれしい

**Comment by yuji-shimoda** [comment]
GitHub のプロフィールページにアクセスして URL に表示されているユーザー名（ユーザID　私の場合だと、yuji-shimoda）が確か、API 越しで取得出来る nickname だったと思います。API 越しで取得出来る name が、"Yuji Shimoda" だったはず
記憶違いだったらごめんなさい。

**Comment by yuji-shimoda** [comment]
rubyist-connect は、GitHub だけは GitHub の仕様に合わせていたはずなので
すべてのユーザIDを横断的に検索したい場合は、GitHub のみ nickname で検索しないといけないはずですね。現状、rubyist-connect の GitHub アカウント検索機能は name で検索されている？

**Comment by toshima66** [comment]
チーム: Bです。

**原因**
本番データの nickname に t_oginogin のデータが入っていたために発生していました。
おそらく、nickname カラムが追加されたタイミングなどでデータの不整合が発生していたのではないかと思われる。詳細は闇。。

**対応**
本番データの修正を行っていただき。対応完了としました。
なお、他のデータは問題なしだったようでした。

**Comment by yuji-shimoda** [comment]
対応ありがとうございます。
