### ISSUE TITLE
自己紹介が空欄のユーザーは一覧に表示しない

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#127]
「とりあえず覗いてみただけ」というユーザーが一覧に表示されるとノイズになるので、自己紹介が入力されているかどうかで利用に前向きなユーザーかどうかを判断する。
（夕方に下田さんやAkiさんと議論してた件です）

**Comment by JunichiIto** [comment]
この仕様に関連して、自己紹介が空欄のユーザーはログイン直後にプロフィール画面へ遷移させる。

前向きなユーザーは何か書いてくれるだろうし、やる気の無いユーザーは毎回ここをスルーして他の情報を見にいくはず。

https://github.com/yuji-shimoda/rubyist-connect/issues/79

**Comment by yuji-shimoda** [comment]
はい、自己紹介欄が未入力のユーザはプロフィール画面へ遷移させる仕様だと
ファーストログインのユーザにも優しいと思いますし、私は賛成です。
あと、User モデルに出身地（居住地？）を入力するのを促しておけばリージョンを
分ける際にスムーズと感じました。

**Comment by yuji-shimoda** [comment]
ちなみに、居住地はプルダウン形式で県を表示させて入力させる方式が良いのではと
Aki さんにコメント頂きました。これは、別 issue ですね

**Comment by JunichiIto** [comment]
居住地の件は以下のissueに書きました。

https://github.com/yuji-shimoda/rubyist-connect/issues/138

**Comment by JunichiIto** [comment]
@m-taira さんが対応してくれたのでcloseします。どうもありがとう！！

https://github.com/yuji-shimoda/rubyist-connect/pull/142
