### ISSUE TITLE
タグ機能の（一時）廃止

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#128]
タグ機能、どういう仕様になっていて、どういう活用をすればいいのか、いまいちハッキリしておらず、開発する側にとっても利用する側にとっても混乱の元になりそうなので、いったんコードごと消してしまうのが良いのでは？

タグ機能については方向性がハッキリしたタイミングでゼロから再構築するのがよいと思います。

**Comment by yuji-shimoda** [comment]
はい、タグ機能は一旦リセットで問題無いです。

**Comment by JunichiIto** [comment]
バイバイ、タグ機能。
