### ISSUE TITLE
github/twitterのIDでユーザー検索したい

### ISSUE THREAD

**Issue by hilohiro** [rubyist-connect/rubyist-connect#13]

**Comment by yuji-shimoda** [comment]
これは、文字列で検索したいってことですよね？

**Comment by hilohiro** [comment]
そうですね。github/twitterのユーザーIDを入力して検索すると、そのIDを持っている人を表示する動作です。

**Comment by yuji-shimoda** [comment]
Ransackを使う
https://github.com/yuji-shimoda/rubyist-connect/blob/master/app/models/user.rb#L31

**Comment by yuji-shimoda** [comment]
User 以外のリソースで検索出来るようになれば、placeholder の "User" を削除する
https://github.com/yuji-shimoda/rubyist-connect/blob/master/app/views/layouts/application.html.slim#L31

**Comment by tanaka-yoshi10** [comment]
対応しました
https://github.com/yuji-shimoda/rubyist-connect/pull/114
