### ISSUE TITLE
sign out のリンクを、アイコンに変更する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#130]
ひとまず、fa-sign-out に変更すれば良いかも
http://fortawesome.github.io/Font-Awesome/icon/sign-out/

**Comment by yamasy1549** [comment]
ついでにline-heightも調整して、アイコンが中央に来るようにしておきます！

**Comment by yuji-shimoda** [comment]
production に deploy 済みで問題無さそうなので、クローズします。
