### ISSUE TITLE
よくある質問ページを作る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#131]
サービスの目的や簡単な操作説明を載せておく。
GitHubのWikiにFAQページを作って、そこへリンクを張るだけでもOK。

こういうリンクってよくあるのは「フッターに表示」かな？

**Comment by JunichiIto** [comment]
FAQページには「その他、質問やご要望はGitHub issueからどうぞ。 => https://github.com/yuji-shimoda/rubyist-connect/issues/new 」みたいな項目も作る。

**Comment by yuji-shimoda** [comment]
そうなると、そろそろ Organization account にリポジトリを移管する感じでしょうか？

**Comment by JunichiIto** [comment]
んー、別にWikiページが下田さんリポジトリにあっても問題ないのでは？と僕は思ったんですが。
何か思うところがあれば教えてください。

**Comment by yuji-shimoda** [comment]
ライセンスに記載のとおり、開発は rubyist-connect developers に主導権が移った感じなので、
リポジトリも個人ではなくて、Organization account に移管して管理/運営した方が良いのかなと思いました。

**Comment by yuji-shimoda** [comment]
ちなみに、現状 Wiki ページが私のリポジトリにあっても、問題は無いですー。

**Comment by yuji-shimoda** [comment]
よくあるご質問（FAQ）

### GitHub のアカウント登録をしていないのですが、Rubyist Connect を利用することはできますか？

GitHub アカウントが必要なサービスであるため、利用することはできません。
お手数ですが、[GitHub](https://github.com/)の Sign up for GitHub からアカウントを登録してください。

### Rubyist Connect にログインする度に毎回、ユーザー登録のページに飛ばされます。どうすれば一覧のページを表示できますか？

Rubyist Connect は、Rubyist が Rubyist を見付ける手助けをするために運営されています。
自己紹介の文章が登録されていないユーザーは、自己紹介の文章を登録頂くようにユーザー登録のページに遷移します。
自己紹介文章を登録頂くことで、ログイン後すぐに一覧のページを表示することができます。
お手数ですが、自己紹介文章をご記入いただき登録ください。

### 勉強会で Rubyist Connect を利用したいと考えています。利用方法を教えてください。

Rubyist Connect にログイン後、メニューバーのカレンダー・アイコン（Events）ボタンをクリックし、
new event のリンクからイベントを作成してください。イベント名は、セミナー、イベント、勉強会名で結構です。
イベントに参加するユーザーをリストからチェック・ボックスで選択し、ご登録頂くことでイベントが作成されます。

### イベントを作成したいのですが、イベントに参加予定のユーザがリストに表示されません。表示させる方法を教えてください。

自己紹介文章を登録されていないユーザは、イベント作成時の一覧に表示されないため
イベントを作成する前に自己紹介文章をユーザに登録して貰ってください。

### メニューバーに設置された検索機能（User Search）では、何の情報でユーザを検索していますか？

現在は、GitHub ユーザID/Twitter ID/Facebook ID/Qiita ID を元にユーザを検索しています。

### 退会したいのですが、退会手順をおしえてください。

ユーザー情報の登録ページから、退会ボタンをクリックすることで退会できます。

**Comment by JunichiIto** [comment]
細かい点はさておき、全体的によいと思います－ :+1:

**Comment by JunichiIto** [comment]
> 勉強会で Rubyist Connect を利用したいと考えています。利用方法を教えてください。

ここは「Q.イベント機能とは何ですか？」「A.勉強会の参加者をグルーピングする機能です」みたいな形の方がユーザー目線に立っているかなーと思いました。

**Comment by yuji-shimoda** [comment]
とりあえず、ブレストして後でWikiに纏める予定です！

**Comment by yuji-shimoda** [comment]
FAQ の Wiki を作成しましたー。
https://github.com/rubyist-connect/rubyist-connect/wiki/FAQ

**Comment by springaki** [comment]
:+1:
