### ISSUE TITLE
イベント編集ページでユーザーの選択をもっとリッチにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#133]
イメージ的にはこんな感じ？

http://kwski.net/jquery/1081/

**Comment by JunichiIto** [comment]
人数が増えるとやばい。
UI的にはどう解決すべきだろうか。。。

![screen shot 2015-01-17 at 18 17 32](https://cloud.githubusercontent.com/assets/1148320/5788376/4d39e9d6-9e75-11e4-8c95-72441e8d978b.png)

**Comment by yuji-shimoda** [comment]
これは、かなり厳しいですね :sweat:

**Comment by yuji-shimoda** [comment]
実は、これもリージョン機能で表示するユーザを絞り込んでいれば解決するのでは？

**Comment by yuji-shimoda** [comment]
ただし、同一リージョン内にたくさんのユーザがいると同じことですね。
ここまでサービスがスケールすると Doorkeeper からユーザ一覧を引っ張ってこないといけないかも

**Comment by JunichiIto** [comment]
Doorkeeper Syncで改善されたのでいったんクローズ。
