### ISSUE TITLE
トップページのアラートをわかりやすい場所に表示する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#134]
今は画面の一番下にあって見づらい。
画面を開いたらすぐ目に付く場所に表示したい。

**Comment by tanaka-yoshi10** [comment]
実はこのアラート不要ではないでしょうか。
Twitter,Facebookもログアウト時に特に表示はしていないようです。

トップページにアラートを出すシーンがログアウトの他にないのであれば、
アラートを消すというのはどうでしょうか。

**Comment by JunichiIto** [comment]
@tanaka-yoshi10 ログイン失敗時にアラートを表示したりする可能性もあるので、やはり表示場所は直しておきたいです。

**Comment by toshima66** [comment]
@JunichiIto かぶってしまいますが。こんな感じでどうでしょうか？

![development rubyist connect-1](https://cloud.githubusercontent.com/assets/904191/6095658/73425b6e-afa9-11e4-9d6a-9f5af39765d1.png)
