### ISSUE TITLE
ベータ版であることを明記する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#135]
まだまだ発展途中なので。

**Comment by yuji-shimoda** [comment]
TOP の Rubyist Connect 横に小さく beta と表示するのが一番、目に付く気がします。

**Comment by JunichiIto** [comment]
そんな感じですね。＞Rubyist Connect 横に小さく beta と表示

**Comment by kanizmb** [comment]
こちら私の方で対応しますー

**Comment by yuji-shimoda** [comment]
@kanizmb よろしくお願いしますー

**Comment by yuji-shimoda** [comment]
production に deploy 済みです！クローズしますー
