### ISSUE TITLE
機能追加やバグ修正のお知らせ欄を作る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#136]
けど、毎回更新するのはが面倒かも・・・。

**Comment by yuji-shimoda** [comment]
rubyist-connect の Twitter アカウントを作成して、そこでアナウンスしておくのが楽でしょうか？

**Comment by JunichiIto** [comment]
Twitterだと、どんどん流れていってしまうのでちょっと違う気が。
なんらのページはいる気がします。

とはいえ、TwitterやFacebookページがあると、ユーザーとコミュニケーションが取りやすいので別件で検討してみましょう。

**Comment by yuji-shimoda** [comment]
Twitter アカウントは、開設しました！

**Comment by yuji-shimoda** [comment]
これも Wiki で作成します？それとも、GitHub Pages 立ち上げます？

**Comment by JunichiIto** [comment]
どっちがいいだろう？Wikiしか考えてなかったけど、GitHub pagesの方がデザインを自由に変えれてベターかな？

**Comment by yuji-shimoda** [comment]
メンテナンスコストを考えると、Wiki がリーズナブルなので Wiki にします。

**Comment by yuji-shimoda** [comment]
## リリースノート

### 2015/01/10 [KRC ハッカソン](http://nishiwaki-koberb.doorkeeper.jp/events/18705)にて追加された機能一覧
- ユーザ一覧ページのユーザ表示順序を、変更しました。（新規ユーザーが上位に表示されます）
- ユーザ一覧のページに、ページネーション機能を追加しました。
- サイト・デザインを大幅に変更しました。（トップ、メインページのデザインとfavicon の追加）
- ユーザー情報に Qiita リンク機能と、年齢表示機能を追加しました。(生年月日を入力し、自動計算します）
- 自己紹介文を、Markdown で記入するように変更しました。
- セミナー、勉強会、イベントなどを管理するための機能を追加しました。
- 検索したユーザーが見付からなかった場合に、該当ユーザーがいない旨を表示するように変更しました。
- ユーザを GitHub ID/Twitter ID/Facebook ID/Qiita ID で検索するように変更しました。

**Comment by yuji-shimoda** [comment]
とりあえず、コミットを追いかけてリストにしています。抜けや漏れや、誤りがあればご指摘ください。お願いします。

**Comment by yuji-shimoda** [comment]
### 2015/01/11
- サイト・デザインを変更しました。（beta サービスであることを明記、sign out のリンクをアイコン化、アイコンの説明を吹き出しで表示）
- 自己紹介の文章を登録していないユーザーは、自己紹介の文章登録を促すために
  ログイン後、設定ページに転送されるようになりました。

### 2015/01/12
- Rails 4.2 にアップデートされました。Rails 4.2 リリースノートは、[こちら](http://railsguides.jp/4_2_release_notes.html)
- 早期リリースされていた、タグ機能が削除されました。 
- サイト・デザインを変更しました。（イベントアイコンの表示場所）
- サイト名が "Kobe Rubyist Connect" から、"Rubyist Connect" に変更されました。
- イベントに追加するユーザ一一覧から、自己紹介文章を未入力のユーザは除外するように変更しました。

### 2015/01/15
- Qiita 公式アイコンを利用するように変更しました。（[Increments株式会社](http://increments.co.jp/)の許諾済み）

### 2015/01/16
- サイトURLが、http://kobe.rubyist.co/ から http://rubyist.co/ に変更されました。

### 2015/01/17
- トップページの more ボタンから、ログインできるように変更しました。

**Comment by yuji-shimoda** [comment]
上記の記載内容に問題が無ければ、Wiki へページ作成します。

**Comment by yuji-shimoda** [comment]
Wiki にリリースノートを作成しました！
https://github.com/rubyist-connect/rubyist-connect/wiki/ReleaseNotes

**Comment by JunichiIto** [comment]
@yuji-shimoda 作成ありがとうございます！
新しい情報が上に来るように書き直しました。

細かい話をつらつら書くと読む人がしんどいので、大きな変更だけを挙げるようにしたいですね。

**Comment by yuji-shimoda** [comment]
新しいお知らせが上に来る方が良いですね :+1: ありがとうございます
