### ISSUE TITLE
住んでいる都道府県の選択と、市区町村の入力ができるようにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#138]
いくつか入力パターンが考えられそうです。
- 住んでる都道府県を選択する
- 住んでる地域（関西、四国、関東等）を選択する
- よく参加する勉強会の地域を選択する
- 地域を1つだけ選択する or 複数選択できる

個人的には「よく参加する勉強会の地域を複数選択する」というのが、一番いいのかな〜と思ったり。

たとえば弘野さんだったら、山陰地方と関西地方のRubyistとつながりたい、というニーズがありそう。

住んでる地域、ってしちゃうと山陰地方（または鳥取県）しか選べなくなってしまう。

**Comment by yuji-shimoda** [comment]
都道府県で入力して貰って、表示する時は少し広い地域で表示するように
すれば良いかなと考えています（いずれは）。現状の登録者を考えると、
居住地域は散らばっていないと考えますが、その判断材料としても、
居住地域の入力を促したいです。

**Comment by JunichiIto** [comment]
じゃあ、いったんは居住地を入力、一覧表示はその都道府県が含まれる地域（関西、四国等）にする、って感じにしますかねー。

発展形としては、「興味のある都道府県（一覧表示の対象にしたい都道府県）をユーザーが取捨選択できる」みたいな仕様が考えられるかも。（これは後回しでOK）

あと、自己紹介と同じく、都道府県も入力していないとログイン直後に編集画面に飛ばされる仕様にしたい。

最後に、任意入力項目として市区町村も入れられる（フリー入力のテキストボックス）、というのはどうでしょう？

**Comment by yuji-shimoda** [comment]
はい、県の入力だけだと Rubyist との近さが感じられないので市区町村も入力出来るのは賛成です。

**Comment by springaki** [comment]
> あと、自己紹介と同じく、都道府県も入力していないとログイン直後に編集画面に飛ばされる仕様にしたい。

素晴らしい !

> 最後に、任意入力項目として市区町村も入れられる（フリー入力のテキストボックス）、というのはどうでしょう？

神戸市とか西脇市が入れられる !! :+1:

**Comment by JunichiIto** [comment]
この機能が実装されたら、今の場所っていう項目は不要になりますね。

**Comment by yuji-shimoda** [comment]
海外の Rubyist が登録することも想定し、"outside japan" も追加する

**Comment by JunichiIto** [comment]
Qiitaになんかこんなgemの紹介が！！

世界の国とその地域名を入手する方法
http://qiita.com/Yoshi66/items/d62e0702638b15cde09d

もしかすると国際化もこれで事足りるかも？？

**Comment by yuji-shimoda** [comment]
heroku に demo app が公開されてました。
http://carmen-rails-demo.herokuapp.com/

都道府県は、日本語ロケールに変更しても漢字になりませんでしたが
そこだけ修正すれば大丈夫っぽいですね :+1:

**Comment by yuji-shimoda** [comment]
ただし、github のリポジトリには、メンテナンスする余裕がないから
まともにしていないよと記載されていますね。
https://github.com/jim/carmen-rails

**Comment by yuji-shimoda** [comment]
carmen-rails で、デフォルトを英語ロケールに変更し、country_code を User model に save 出来るところまでは出来たんですが country_code から subregion_select を呼び出す方法がわからず悩んでいます :sweat:

**Comment by JunichiIto** [comment]
デモサイトを見てみました。
Rubyist Connectの使用目的にかなり合致しているので活用してみたいですね－。
ただ、ちょっと時間がないので今は下田さんのお手伝いはできないかも。。
最悪、勉強会当日に誰かに手伝ってもらう感じになるかな～。

**Comment by JunichiIto** [comment]
もしくは作成途中のブランチをGitHubにpushしてもらったら、他の人がそこからpullして続きを手伝えるかな？
どこでどう困っているのかはコードと画面の動きを見てみないと何とも言えないので。

**Comment by t-oginogin** [comment]
週末なら手伝えるのでブランチあげといてもらえるとうれしいです。

**Comment by yuji-shimoda** [comment]
@JunichiIto @t-oginogin リプライありがとうございますー。週末まで頑張ってみて、出来ても出来なくてもひとまず自分のローカルリポジトリに commit します！

**Comment by yuji-shimoda** [comment]
ひとまず、User モデルに country_code と、state_code を save 出来るようにはなりました。が、rspec が修正出来ていないので users_spec でこけます :sweat: 
綺麗に表示出来ていないので、デザイン部分も修正が必要です。
現状のコードを、自分のローカルブランチに commit しておきます。

**Comment by yuji-shimoda** [comment]
修正ファイルの一覧は、以下です。
https://github.com/yuji-shimoda/rubyist-connect/commit/0219ee8bb6a296e2e49d65fcf4c8d0d09e9690de

**Comment by yuji-shimoda** [comment]
![2015-01-22 11 04 58](https://cloud.githubusercontent.com/assets/2437500/5856978/2c74a5dc-a28b-11e4-971a-c74d76e618bf.png)
キャプチャは、こんな感じです。

**Comment by t-oginogin** [comment]
コードを見ての予想ですが、subregion_selectに渡すcountry_codeをどうやって渡すか？の部分で悩んでいたということでしょうか？
そしてf.object.country_codeという形で入力値を取得できることがわかって解決したということでしょうか？（このやり方は知りませんでした！）

**Comment by yuji-shimoda** [comment]
いえ、お恥ずかしい話ですが以下のセットアップガイドをコピペしてたのが
原因でした。
https://github.com/jim/carmen-demo-app#readme
erb のコードを slim に変換して、そのまま利用していたんですが
モデル名の order と書いてあるところをそのまま利用していたせいで
User モデルに save 出来ていませんでした。 :sweat:

**Comment by yuji-shimoda** [comment]
この機能から、Ruby Kaigi 2016 で掲示されていた Rubyist の World Map みたいなことを
Rubyist Connect 上でしたいなぁと考えてます。

以下の Blog Post の世界地図の写真みたいなイメージです。
https://aaronlasseigne.com/2016/09/15/rubykaigi-2016/

**Comment by JunichiIto** [comment]
そうですね、実現できると面白そうですが、なかなか大変そう・・・。

**Comment by yuji-shimoda** [comment]
どうやって実装するかは、現状の私のスキルレベルでは
想像出来ませんでした。 :sweat:
