### ISSUE TITLE
TOPページの more ボタンのリンク先がない

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#141]
TOPに表示されていないメンバーを追加で表示するのか、ログインさせるのかどちらを想定しておりますでしょうか？

**Comment by JunichiIto** [comment]
もっと見たい人はログインしてね！という動きがいいかなーと思います。

**Comment by yuji-shimoda** [comment]
ログインの方向で問題無いですよね！ リンク先を http://kobe.rubyist.co/users/auth/github に設定するだけでしょうか？

**Comment by kanizmb** [comment]
ログインの想定でした。
リンクの貼り方がわからず保留のままコミットしてたのを忘れていました。すみません :bow:

**Comment by yuji-shimoda** [comment]
全然、大丈夫ですよー :+1:
