### ISSUE TITLE
ページのタイトルを動的に変更する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#147]
今どのページにいるのか、というのがわかるように。

titleをスマートに管理するgemとか、なんかあるのかな？

**Comment by Koichi-Kobayashi** [comment]
パンくずリストとか？

http://muryoimpl.com/blog/2014/04/03/gertel-gem/

**Comment by JunichiIto** [comment]
パンくずは別件ですね～。

僕が意図していたのはタブに表示されるタイトルのことでした。

![screen shot 2015-01-12 at 6 32 19](https://cloud.githubusercontent.com/assets/1148320/5696928/fb4d779a-9a24-11e4-8bdf-7175b1956f79.png)

**Comment by Koichi-Kobayashi** [comment]
そっちな感じがしてました。。
タブの幅に収まるのか・・・ってのも気になりますね。

meta-tagsとか？
http://morizyun.github.io/blog/meta-tags-sitemap-generator-rails-seo/

**Comment by JunichiIto** [comment]
タブの幅の問題は無視してもいいかなーと思ってます。
とりあえず動的に変わればOK、ってな感じです。

紹介してもらったmeta-tagsはちょっと高機能すぎるかなーという気もしますね。。。
SEOを重視するなら有効そうですけど、今の時点ではそこまで考えていないので。
もうちょっとシンプルなgemがあったらいいな～。

**Comment by yuji-shimoda** [comment]
ページタイトルの Kobe も外しちゃいますか？

**Comment by JunichiIto** [comment]
アプリがだいぶん進化しつつあるので、あえてKobeに限定する必要性も薄れてきてる気がしますね。
そろそろ改名する時期かな？

**Comment by JunichiIto** [comment]
ユーザー詳細ページはユーザーの名前を表示する方が良いと思いました。

![screen shot 2015-09-21 at 13 51 42](https://cloud.githubusercontent.com/assets/1148320/9985508/1b44cb2a-6068-11e5-9f8b-f4232f8c2673.png)

「ユーザー表示」と書かれてもあまり嬉しくない。。

イベント表示の場合も同様ですね。

http://rubyist.co/nnect/events/11

全体的に見直した方が良さそうです。

**Comment by soruma** [comment]
> 全体的に見直した方が良さそうです。

次のページのタイトルは変更した方が良いと思います。

* `/:nickname`: ユーザー表示 | Rubyist Connect :arrow_right: 原田 優奈 | Rubyist Connect
* `/events/:id`: イベント表示 | Rubyist Connect :arrow_right: Rubyハッカソン in 大さくら村 | Rubyist Connect

次のページは変更しなくても良いと思います。

* `/`: ユーザー | Rubyist Connect
* `/edit`: ユーザー編集 | Rubyist Connect
* `/events`: イベント | Rubyist Connect
* `/events/new`: イベント作成 | Rubyist Connect
* `/events/:id/edit`: イベント編集 | Rubyist Connect

**Comment by JunichiIto** [comment]
検討ありがとうございます。こちらも後日確認しますね。

**Comment by JunichiIto** [comment]
@soruma 確認しました。
たしかにユーザー表示とイベント表示の部分が変わるだけで、かなり改善される気がしますね。
方針は良いと思います🙆‍♂️
