### ISSUE TITLE
もっとたくさんメンバーを見渡したい（ユーザー一覧の改善もろもろ）

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#148]
現状のユーザー一覧だと、僕のMacBroで6人ぐらいのメンバーしか表示されない。  
画面の右半分もほとんど空きスペースになっている。

![screen shot 2015-01-12 at 6 24 03](https://cloud.githubusercontent.com/assets/1148320/5696899/d2e1b4f2-9a23-11e4-8636-90e165999f5e.png)

だんだんメンバーが増えてきているので、スクロールせずにもっとたくさんのメンバーを見渡せるような画面デザインにしたい。

今のユーザー一覧よりも、トップページのアイコン一覧の方が「にぎやか」な感じがして、楽しそう。

どこか参考になりそうなサイトはあるかな～？たとえば「スタック・オーバーフロー」とか？

http://ja.stackoverflow.com/users

![screen shot 2015-01-12 at 6 29 53](https://cloud.githubusercontent.com/assets/1148320/5696915/80c53062-9a24-11e4-8d23-a1184377327f.png)

**Comment by kanizmb** [comment]
#118 より転載
![c664f4ee-98cc-11e4-99d7-d6749470d303](https://cloud.githubusercontent.com/assets/7820884/5690881/090d1b7c-98ec-11e4-9e4d-cf1d22544463.png)

**Comment by JunichiIto** [comment]
参考：自分のデータは先頭に表示したい、というissueも挙げていました。

https://github.com/rubyist-connect/rubyist-connect/issues/208

**Comment by JunichiIto** [comment]
マークダウンは無効にしてプレーンテキストとして表示する、という意見も出ています。

**Comment by yuji-shimoda** [comment]
自分のデータは、上部右側に小さく表示しユーザ一覧の表示数を増やした方が良い気がしてきました。

**Comment by yuji-shimoda** [comment]
![2015-05-23 10 06 34](https://cloud.githubusercontent.com/assets/2437500/7782628/fc8f95c2-015b-11e5-993f-69e458fa6fce.png)

**Comment by yuji-shimoda** [comment]
![2015-05-23 15 00 03](https://cloud.githubusercontent.com/assets/2437500/7782642/79ae5bc4-015c-11e5-8dd1-043d4352ffb2.png)

**Comment by yuji-shimoda** [comment]
ユーザ一の表示数を増やすより、スクロールせずに１画面で収まったほうが良いかなと思い
変更してみました。いかがでしょうか？

**Comment by JunichiIto** [comment]
基本的に悪くないと思います。

細かい点でいうと、[StackOverflowのユーザー一覧](http://ja.stackoverflow.com/users)を参考にしたらもっと良いかなと思いました。
- 自分のアイコンは検索ボックスの左に移動する（ログアウトボタンは一番右の方が落ち着く）
- 「メンバー一覧」のような見出しがないと、何の情報を一覧表示しているのかわかりづらい。

![screen shot 2015-05-24 at 8 18 05](https://cloud.githubusercontent.com/assets/1148320/7786058/dfd3e158-01ed-11e5-84b8-1f34280acca1.png)
