### ISSUE TITLE
Qiitaアイコンの見栄えを良くする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#153]
機能的な問題は無いといえ、せっかくクールなデザインをスポイルしちゃいそうなので、いい感じに変えたいなあ。

**Comment by JunichiIto** [comment]
FontAwesomeではないけど、この画像を使ってみるとか。

![qiita](https://cloud.githubusercontent.com/assets/1148320/5697826/5959416a-9a3f-11e4-8d11-838a8195c97e.png)

![qiita-2](https://cloud.githubusercontent.com/assets/1148320/5697827/5be385ee-9a3f-11e4-905b-98b9aa619a8b.png)

ちなみに画像はここから取ってきて、モノクロ変換は僕の方でやりました。（著作権うんぬんの話になるとややこしいけど。。。）

http://qiita.com/icons/favicons/public/apple-touch-icon.png

**Comment by yuji-shimoda** [comment]
Qiita のicon、確かに気になりますよねー

**Comment by kanizmb** [comment]
なんとかしてみますー

**Comment by tanaka-yoshi10** [comment]
FontAwesomeでなんとかしようと試行錯誤してみましたが難しかったので、画像でできた方が柔軟性があっていいのでと思いました。(FontAwesomeのことをわかってなかっただけかもしれないですが)

**Comment by kanizmb** [comment]
進捗です
![image](https://cloud.githubusercontent.com/assets/4459676/5699323/3e7c6a24-9a68-11e4-8ef0-19105ea532cf.png)

**Comment by yuji-shimoda** [comment]
:+1:

**Comment by JunichiIto** [comment]
いいね！

**Comment by JunichiIto** [comment]
:tada: https://github.com/yuji-shimoda/rubyist-connect/pull/163
