### ISSUE TITLE
トップページの fontawesome アイコン部分をヘルパーメソッドを使った書き方に変更

### ISSUE THREAD

**Issue by kanizmb** [rubyist-connect/rubyist-connect#155]
```
i.fa.fa-github-square
```

のようにHTMLでベタ書きされているところを、

```
= fa_icon 'github-square'
```

のようにヘルパーメソッドを使った書き方に変更する。
#### 参考

[RailsにFont Awesomeを導入するGem - Qiita](http://qiita.com/succi0303/items/7f76d53ebe54dab41124)

**Comment by JunichiIto** [comment]
そういうリファクタリング、個人的には好きです！！

**Comment by springaki** [comment]
いいですね !!
余談ですが、i tag を使ってる理由ってなにかあるんですか？

**Comment by kanizmb** [comment]
:smile: 

@springaki 
font awesome 公式で iタグがサンプルとして載っているからで、個人的に深い意味はありませんー。
http://fortawesome.github.io/Font-Awesome/icon/gamepad/

**Comment by springaki** [comment]
@kanizmb おぉー本当だ。そういうものなんですねー。なんか i tag の趣旨とちょっと違うのかと思ってたので不思議だったのでした。

**Comment by JunichiIto** [comment]
> 余談ですが、i tag を使ってる理由ってなにかあるんですか？

アイコン = iタグ、は最近よく見かけるパターンですね。
ちょっと調べてみました。

http://stackoverflow.com/questions/11135261/should-i-use-i-tag-for-icons-instead-of-span

ベストアンサーを要約すると、
- 短く書ける
- iconのiのように見える
- HTMLの意味よりも記述スピードが重視されたバッドプラクティスだ

と書かれていますね。
「iconのiみたいだから、iタグでいいじゃん」っていうことみたいですw

**Comment by springaki** [comment]
おぉ〜なるほど。そんなんでいいの？ww
ありがとうございます。:smile:
