### ISSUE TITLE
トップページの new member アイコンにユーザー名の入ったtooltipを付ける

### ISSUE THREAD

**Issue by kanizmb** [rubyist-connect/rubyist-connect#156]
未ログイン時トップページの new member アイコン部分、
デフォルトアイコンだと見分けがつかないので、補足情報として
- マウスオーバーした時（PC）
- touch した時（スマートフォン）

に、tooltip でユーザー名が出ても良いかなと思います。
（画面がごちゃつくので、常時表示じゃない方が良さそう？）

作業優先度は低です。
#### 実装方法参考
- #144
- #1 の [Tooltipster - The jQuery Tooltip Plugin](http://iamceege.github.io/tooltipster/) 
#### 実装したい箇所

![image](https://cloud.githubusercontent.com/assets/4459676/5698103/68a90322-9a48-11e4-8559-c7c104a97ed3.png)

**Comment by yuji-shimoda** [comment]
同意します。＃github のIDを表示するようにしておけば良いかも

**Comment by JunichiIto** [comment]
いいと思います！
大した機能ではないけど、そういう「おもてなし感」がアプリのUXを改善する鍵なのかも？と思う今日この頃。

というわけで、早目にやっちゃってもいいんじゃないでしょうか？

**Comment by yuji-shimoda** [comment]
new member を辞めて、contributor にしてしまうのはどうでしょうか？ #60

**Comment by t-oginogin** [comment]
トップページのメンバーですが、new member、contributor #60 、ランダム #160と案が出てますが、私はトップページはランダムにして、contributorは別ページで良いかと思います。

**Comment by yuji-shimoda** [comment]
はい、その予定です :+1:

**Comment by t-oginogin** [comment]
了解です〜
