### ISSUE TITLE
TOPページの Author を変更する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#157]
yuji_shimoda -> rubyist-connect developers に変更

**Comment by yuji-shimoda** [comment]
ついでにタイトルの Kobe も外しちゃってよいでしょうか？

**Comment by JunichiIto** [comment]
思い切ってKobe外しちゃいますか！

**Comment by JunichiIto** [comment]
rubyist-connect developers = 西脇.rb＆神戸.rbなのでは？（まあ現状は、ですが）

てか、西脇.rb＆神戸.rbの名前が出てないなら、コミュニティの宣伝も兼ねてどこかに載せたいなーと思ったり。

**Comment by yuji-shimoda** [comment]
現状は、rubyist-connect developers = 西脇.rb＆神戸.rb　かも
ふと考えましたが、自分はどちらのコミュニティ所属だろうと考えてしまいました :sweat:

**Comment by JunichiIto** [comment]
> 自分はどちらのコミュニティ所属だろう

そこは深く考えちゃダメです。
その場のノリで、適当に答えるのが正解w

**Comment by springaki** [comment]
> > 自分はどちらのコミュニティ所属だろう
> 
> その場のノリで、適当に答えるのが正解w

両方なんじゃないですかねー :sweat:

**Comment by JunichiIto** [comment]
いや、両方なんだけど、毎回「西脇.rb＆神戸.rb」って長いでしょ？
だから頭にぱっと浮かんだ方で話したり書いたりしてもらったら良いです、という意味でしたw

**Comment by JunichiIto** [comment]
で、これどうしましょう？

https://github.com/yuji-shimoda/rubyist-connect/pull/159

今のところ西脇.rb＆神戸.rbでしか開発していないので、

``` ruby
| Authored by
= link_to 'Nishiwaki.rb & Kobe.rb', 'http://nishiwaki-koberb.doorkeeper.jp/', target: '_blank'
```

ってしたいなー、というのが僕個人の意見です。

**Comment by yuji-shimoda** [comment]
現状だと、上記の案で問題無さそうです。
新しく外部(西脇.rb＆神戸.rb以外のコミュニティ所属)の方が join した場合は、
どんどん長くなりそうだけど

**Comment by JunichiIto** [comment]
いったん Nishiwaki.rb & Kobe.rbにさせてもらいました。
何か不都合があればまた議論させてください。

https://github.com/yuji-shimoda/rubyist-connect/pull/178

**Comment by yuji-shimoda** [comment]
:+1:
