### ISSUE TITLE
TwitterアカウントやFacebookページを作る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#161]
ユーザーとのコミュニケーションツールとして活用する。

**Comment by yuji-shimoda** [comment]
Twitter は、こちらです。https://twitter.com/RubyistConnect

**Comment by yuji-shimoda** [comment]
Facebook ページは、作ったことが無いのですが簡単ですか？

**Comment by JunichiIto** [comment]
簡単に作れますよー。
ネットをググれば情報がたくさん見つかるはず。

**Comment by yuji-shimoda** [comment]
Facebook ページは、サブドメインの移行とリポジトリの Org 移行が完了してから着手します。

**Comment by yuji-shimoda** [comment]
Facebook ページを作成しましたー
https://www.facebook.com/Rubyist.Connect
