### ISSUE TITLE
フォント用のスタイルシートを scss から sass に書き直す

### ISSUE THREAD

**Issue by kanizmb** [rubyist-connect/rubyist-connect#167]
https://github.com/yuji-shimoda/rubyist-connect/blob/master/app/assets/stylesheets/fonts.css.scss
変更しようと思って忘れてました。

**Comment by JunichiIto** [comment]
念のため確認ですが

http://css2sass.herokuapp.com

や

https://html2slim.herokuapp.com

はご存知ということでOKですよね？

**Comment by kanizmb** [comment]
記憶の彼方にうっすら見覚えがありますが、sassやslimを覚えたいという気持ちもあり、変換サービスを使うのは完全に思いついていませんでした！
お手本として変換して調べるというのをやればよかったです。

**Comment by JunichiIto** [comment]
あ、今まで手作業で変換してたんですね。
僕は最初っから変換サービスを使ってます ^^;

同じような変換サイトで

http://js2coffee.org/

とか

http://html2haml.herokuapp.com/

みたいなサイトもあるので、「言語間の翻訳」が必要になった場合はこうしたツールを探してみると良いかもしれません。

**Comment by kanizmb** [comment]
効率UPのために先人の労力をどんどん活用していかないとですね！
slim単体ではなく、slim + rails view になった時にわからなくなっているケースもあるので、質問するにしてもその辺をしっかり切り分けて聞くように注意しなければ。

**Comment by yuji-shimoda** [comment]
すみません、この issue は @kanizmb 担当で良いのですか？
それとも、クローズ？

**Comment by kanizmb** [comment]
@yuji-shimoda
担当は私でも、他の方でもかまいません。
他のファイルがすべてsassなので揃えたほうが良いと思っています。

**Comment by kanizmb** [comment]
やってみたんですが、単純に変換するだけではなぜかエラーが...

**Comment by JunichiIto** [comment]
@kanizmb エラー画面のキャプチャやエラーメッセージのコピペを貼ってもらえるとアドバイスしやすくなると思います～。

**Comment by JunichiIto** [comment]
このサイトを使って変換してみました。

http://www.sasstoscss.com/

あと、拡張子もscss => sassに変更しています。

こちらの環境ではこれで動きました。試してみてください。

**Comment by kanizmb** [comment]
今改めてやり直してみたらうまくいきました〜 :sweat_smile: 

ちなみに
- 変換サイトで変換したものはフォントが出ない
- 手入力で変換するとエラー

という状況でした。問題の原因は以下の通りです。

#### 変換サイト

http://css2sass.herokuapp.com/

```
src: url(font-path("qiita_icon.eot") + "?-3zppnw")
```

であるべきところが、

```
src: url(font-path("qiita_icon.eot") (+"?-3zppnw"))
```

となっていた。

#### 手入力時

src: の後ろにスペースが不足していた。

``` sass
@font-face 
  font-family: 'qiita_icon'
  src:url(font-path("qiita_icon.eot") + "?-3zppnw")
  src:url(font-path("qiita_icon.eot") + "?#iefix-3zppnw") format("embedded-opentype"),url(font-path("qiita_icon.woff") + "?-3zppnw") format("woff"),url(font-path("qiita_icon.ttf") + "?-3zppnw") format("truetype"),url(font-path("qiita_icon.svg") + "?-3zppnw#qiita_icon") format("svg")
  font-weight: normal
  font-style: normal
```

**Comment by kanizmb** [comment]
新たに教えていただいた変換サイトでは上記問題は出ませんでした〜 :rocket:
http://www.sasstoscss.com/
