### ISSUE TITLE
GitHub アイコンの動作を GitHub トップページのアイコン動作に合わせる

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#175]
GitHub トップメニューの Octcat アイコンにマウスを合わせた際の青色のイメージです

**Comment by yuji-shimoda** [comment]
本番環境にデプロイしました！

**Comment by JunichiIto** [comment]
ありがとうございます！

悪くはないのですが、こうやって見てみるとアイコンがすべて青系になって、ちょっと「寒い」印象があるかな？と思いました。（今更言うなよ、って感じですが）

![image](https://cloud.githubusercontent.com/assets/1148320/18860337/4c77831c-84b7-11e6-9601-ac29263f4a24.png)

**Comment by yuji-shimoda** [comment]
https://github.com/logos
github サイトの説明では、色の変更はダメよと説明があるので、致し方ないかとー

**Comment by springaki** [comment]
現状、黒or白から青に変えてしまっているのでは !?

**Comment by JunichiIto** [comment]
標準状態は黒、hoverで青、みたいにする方がいいかもですね。

**Comment by yuji-shimoda** [comment]
なるほど、github トップページのアイコン動作に合わせる感じですねー

**Comment by yuji-shimoda** [comment]
イメージとしては、こーゆー感じです。
http://codepen.io/yuji-shimoda/pen/ALrkBx

**Comment by JunichiIto** [comment]
いいと思います－。

**Comment by springaki** [comment]
LGTM

**Comment by yuji-shimoda** [comment]
ありがとうございます。 @JunichiIto @springaki 
ちなみに実際のコードだと、user.github_url.present? の場合のみ
hover でカラーコードを変更する処理を入れないといけないはずなんですが
そもそも GitHub ログインを前提としたサービスなので分岐処理は必要？と疑問に感じていました。

https://github.com/rubyist-connect/rubyist-connect/blob/master/app/views/users/_sns_links.html.slim#L3

別のログイン認証がサポートされて、GitHub ログインが必須じゃなくなった場合に
必要となるコードであることは理解していますが、css 側で fa_icon が active かどうかで
hover の処理を分岐させる？というあたりのコードをどう書けば良いか分かっていないです。

@kanizmb にご指南頂きたいです！

**Comment by yuji-shimoda** [comment]
本番環境にデプロイ済みなのでクローズします！
