### ISSUE TITLE
SNSアカウントがリンクされていない場合は、アイコンを隠したい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#176]
リンクされていないアイコン（クリック出来な）なら、見えない方が良いかなと思いました。

**Comment by JunichiIto** [comment]
うーむ、どっちもメリット、デメリットがありそう。
今の仕様でもリンクは無いよ、っていうのは見て分かるし、アイコンがサービスごとに縦に揃うからこのままでもいいんじゃない？っていう気がします。

**Comment by kanizmb** [comment]
未設定時は #dcdcdc ぐらいの薄グレーにして無効の感じを強調するとよさそうです。
あと一覧ではもっとアイコン小さくて良いと思います。

**Comment by yuji-shimoda** [comment]
確かに、一覧の時はもう少しicon小さくても良い気がします。
あと、PCで閲覧してるときは２列とか３列くらいで表示したいですね！

**Comment by kanizmb** [comment]
> 一覧の時はもう少しicon小さく

[このコミット](https://github.com/yuji-shimoda/rubyist-connect/commit/23a4096c60c65ac5a20b30f6f18105e4e9326113)で、同じpartialでもページごとに別々のstyleが割り当てられるように変更してあるので、ご活用くださいませ〜

例:
https://github.com/yuji-shimoda/rubyist-connect/blob/master/app/assets/stylesheets/users.css.sass

``` sass
.page-users.page-index
  .sns-icons
    //フォントサイズを指定 
```

**Comment by yuji-shimoda** [comment]
改めて見ると、そこまで気にならないような気がしました。
また、綺麗にアイコンが並んでいる方が見栄えがするので現状維持でクローズします。
