### ISSUE TITLE
kobe のサブドメインを変更する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#179]
サービス名的にも kobe が外れましたし、ユーザ（コントリビューター）に弘野さんやmakiさん、pinzolo さんやむらじゅんさんがいるので、kobe を外してもいいかなと思いました。
＃kobe が付いているから、登録しないユーザがいると機会損失になりますし、、、
ただ heroku で運用する以上、サブドメインの方が楽（ルートドメインにするとなると、有料のDNSサービスとか、Amazon Route53 + S3）だし、ルートドメインで運用するメリットはそれほど無い気がするので、この際サブドメインを変更しようと思います。
無難に www.rubyist.co とかで良いかなと。
他に良いサブドメイン名や、反対意見があればコメントお願いします。

**Comment by kanizmb** [comment]
よくわかっていないですがこんな情報ありました。

[Express - herokuにルートドメインを無料で設定する - Qiita](http://qiita.com/Tkashiro/items/8249455477bbb5333118)
[お名前.comを使ってHerokuのルートドメインを設定する - Qiita](http://qiita.com/numa08/items/d4ad9454f0baefc8c784)
[Herokuアプリ:無料で独自ドメインをルートドメインにする - Hello world, I am kgmx.](http://kgmx.hatenablog.com/entry/2014/09/04/090232)

**Comment by yuji-shimoda** [comment]
ルートドメインの設定については、[heroku dev center](https://devcenter.heroku.com/articles/custom-domains) に記載のとおり出来なくも無いんですが、どうしてもルートドメインで運用したいという
強いコダワリがない限り、コストや労力に見合わない気がしています。
また、Rails が動く PaaS で heroku 以上のサービスが見付からなかったというのも理由の１つ。
現状、ドメイン取得のコスト以外は掛かっていませんし出来るところまで heroku で頑張るという
話を、伊藤さんとしていました。とりあえず、サブドメイン運用が一番リーズナブルかと考えています。

**Comment by JunichiIto** [comment]
おや、こんなところにもルートドメイン（ネイキッドドメイン）に関する情報がありますよ～？？
http://blog.jnito.com/entry/2014/05/04/090537

このサイトはルートドメイン + Herokuで運用できてるみたいw
http://coupe-baguette.com/

・・・なんですが、サブドメインは付けておいた方が良いと思います。
ずっとhttpのままならいいんですが、もし将来的にhttpsを利用としたいときにルートドメインが使えないからです。

今のところはhttpsにする予定はないですが、将来絶対無いとは言い切れないので、サブドメインは付けておいた方が無難でしょうね。

付けるとしたらwwwかな～。
それ以外あまりアイデアもないし。

あと考慮する点としては、kobeのサブドメインでアクセスしてきた人をリダイレクトさせるかどうかですね。

**Comment by kanizmb** [comment]
> もし将来的にhttpsを利用としたいときにルートドメインが使えない

むむむ？esa.ioがルートドメインでSSL使えているような。
プランか何かが違うんでしょうか。
[esa.io - we love heroku](http://welove.herokuapp.com/sites/364)

**Comment by yuji-shimoda** [comment]
esa.io は、[dnsimple](https://dnsimple.com/pricing)というサービスを使っているようですね。
$3/m みたいです。

**Comment by JunichiIto** [comment]
なるほど、ANAMEを使えばSSLもいけるのか。

http://qiita.com/Oakbow/items/8f76ca074f51fc3bd89c#2-3

じゃあネイキッドで進めるのもアリかもですね。

http://blog.jnito.com/entry/2014/05/04/090537 で紹介しているCloudFlareは無料で使えますよ。

**Comment by yuji-shimoda** [comment]
ドキュメントがありました。
http://www.higherorderheroku.com/articles/cloudflare-dns-heroku/

**Comment by yuji-shimoda** [comment]
リポジトリの移行に合わせて、DNSとサブドメインからルートドメインに変更しようと考えています。
コメントあればお願いしますー。

**Comment by yuji-shimoda** [comment]
ルートドメインに変更しました。クローズします。
