### ISSUE TITLE
リポジトリを個人からorganizationへ移管する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#185]
Assigneeを柔軟に指定したりできるように。

TODO（随時追加してください）
- [x] gitterへ事前アナウンス
- [x] README > Contributingのリンクを変更する
- [x] GitHub Application の設定移管
- [x] Wiki のリポジトリ情報を更新
- [x] gitterへ事後アナウンス & create & invite (リポジトリ移管とともにgitter room削除されたので)

**Comment by yuji-shimoda** [comment]
本日 1/15 の晩に移行予定です。よろしくお願いします。

**Comment by springaki** [comment]
作業終了〜。おつかれさまでした :smile:
