### ISSUE TITLE
KRCメンバー間で連絡が取り合えるような仕組みがあっても良いかも

### ISSUE THREAD

**Issue by t-oginogin** [rubyist-connect/rubyist-connect#186]
- フォーム入力からメッセージを送れるようにする？
- SlackなどにKRCの部屋を作っておき、KRCからリンクを貼るなどでどうか？

**Comment by yuji-shimoda** [comment]
これは、Twitter とかのサービスを利用して貰えば良いかなぁと考えていましたが
GitHub 以外の SNS アカウントを登録していないユーザに対しては、どーすればいいの？という
疑問が浮かびました。

**Comment by springaki** [comment]
> GitHub 以外の SNS アカウントを登録していないユーザに対しては、どーすればいいの？

そういう人はそういうコミュニケーションを望んでないのじゃないかなーと推測しますが、望んでいるけれど登録してないケースってあるのでしょうかねー？

**Comment by yuji-shimoda** [comment]
確かにTwitterくらいは、登録して欲しいかも。rubyist connect 内でのメッセージ機能は無くて良い気がしますー。READMEに記載の通り、他のサービスで代替出来る機能はあえて作りません。それでも、要望が出てきたら考えましょう :+1:

**Comment by t-oginogin** [comment]
確かにTwitterあれば最初の連絡はとれますね！
というわけで一旦クローズしておきます。

**Comment by yuji-shimoda** [comment]
Rubyist Connect の Slack Team をテスト的に、作成してみても良いかなと考えています。
開発サイドは、gitter があるので困りませんが Rubyist Connect サービスの１ユーザとして利用する
ユーザサイドの視点に立ってみると、気軽にメッセージをやりとり出来る場があっても
いいかなという考え方です。以前、寺田さんに Rubyist Connect の登録ユーザ全員にリーチする
機能ありましたっけ？って言われて考えていました。いかがでしょうか？

**Comment by JunichiIto** [comment]
参考までに、チャットができるようなサービスを作るのは許可がいるみたいですよ。

[ユーザ間でチャットできるWEBサービスの立ち上げで注意すべき法律【電気通信事業法】](http://blogs.itmedia.co.jp/itbengoshi/2015/04/web.html)

なので、少なくともRubyist Connectの中でそういう機能を作るのは避けた方がいいと思います。

**Comment by springaki** [comment]
> 参考までに、チャットができるようなサービスを作るのは許可がいるみたいですよ。
> 
> ユーザ間でチャットできるWEBサービスの立ち上げで注意すべき法律【電気通信事業法】

@JunichiIto えっそうなんだ !? youroomとかもこういう届出を提出してるってことですか？

**Comment by yuji-shimoda** [comment]
コメントありがとうございます。

> 参考までに、チャットができるようなサービスを作るのは許可がいるみたいですよ。
> 
> ユーザ間でチャットできるWEBサービスの立ち上げで注意すべき法律【電気通信事業法】
> 
> なので、少なくともRubyist Connectの中でそういう機能を作るのは避けた方がいいと思います。

Rubyist Connect 内にチャット機能は作らず、外部のチャットサービスへ誘導すれば問題無いですよね？試しに Rubyist Connect の Slack Team を作成してみました。

https://rubyist-connect.slack.com/

メールアドレスでユーザを招待する必要があるのですが、GitHub 連携時に取得した
Eメールアドレス宛てに invite するのはまずいのかな？最初は、身内だけ招待すれば良いですかね？

**Comment by JunichiIto** [comment]
外部サービスへの誘導は大丈夫そうですね。

> 最初は、身内だけ招待すれば良いですかね？

そうですね。背景がわかっている人だけに送信した方がいいと思います。

P.S.  
実はSlackって名前は知ってるけど使ったことはない・・・。

**Comment by springaki** [comment]
もう作ってもらっちゃったのでコメントの出遅れ感がありますが...

> ユーザサイドの視点に立ってみると、気軽にメッセージをやりとり出来る場があっても

ユーザグループとかコミュティのようなものを作りたいのであれば、(invite や 承認が必要な)close team 運用がベースの slack よりは 自分で Join 可能な IRC とか idobata とかの方がより向いてるんじゃないかなーと思いました。

**Comment by yuji-shimoda** [comment]
> ユーザグループとかコミュティのようなものを作りたいのであれば、(invite や 承認が必要な)close team 運用がベースの slack よりは 自分で Join 可能な IRC とか idobata とかの方がより向いてるんじゃないかなーと思いました。

これ（IRCとか idobata）は、Rubyist Connect に join していないユーザも参加可能になってしまいますか？

**Comment by springaki** [comment]
@yuji-shimoda 
設定で切り替え可能だったような。ちょっとハッキリ覚えてないですね。誰でもjoinして欲しいわけではないんですか？
たとえば、ここにアクセスできますか？
general
https://idobata.io/#/organization/rubyist-connect/room/general

もしくは
random
https://idobata.io/organizations/rubyist-connect/rooms/ramdom/join_request/7dbd880e-247a-4b12-8607-1f392b35cd74

**Comment by yuji-shimoda** [comment]
アカウント作成すれば、ゲストでログイン出来るみたいですね。どこまで利用されるか想定していないので、オープンな場が良いのかクローズな場が良いのか判断が難しいところ

**Comment by springaki** [comment]
general の方には入れていますか？ (なにも設定してないので入れない想定)
random の方には入られているのは確認しました ! (guest urlを付けたので入れる想定)

もう一度改めて確認したいのですが、どのような状態を作りたいんでしたっけ？
"ユーザ同士が気軽にメッセージをやりとり出来る場" ですか？ 

それなら 「rubyist connect 使ってる人たちのコミュニティってどんなのかなー？」と潜在ユーザが様子を見られるようにするのもアリかもしれません。サービス登録した人のみに制限したいのであれば(その理由は何故か聞きたいケド...)  rubyist connect の中に guest login url を貼っておいてサービス登録した人だけログインできるようにする。などの運用の仕方が考えられますね。

**Comment by yuji-shimoda** [comment]
general の方は、入室出来ませんでした。

> もう一度改めて確認したいのですが、どのような状態を作りたいんでしたっけ？
> "ユーザ同士が気軽にメッセージをやりとり出来る場" ですか？

この Issue での要望は、以下であるとの理解です。
- 気軽にメッセージをやりとり出来る （荻さんの要望）
- できれば、Rubyist Connect 登録ユーザ全員にリーチしたい（寺田さんの要望）

slack / idobata どちらでも、上記の項目は満たせると考えています。（合ってます？）
個人的には、Rubyist Connect をコミュニティと捉えるか、サービスとして捉えるかで
利用するチャットサービスが変わってくるのでは？と思っています。

現状、Rubyist Connect に登録しているユーザを確認するには 
GitHub アカウントで認証して貰って（join して貰って）ログインすることを
前提としたサービスなので slack の方が合ってるかなぁと思いました。

ただ、Aki さんが言うように Rubyist Connect の Open なチャットサービスがあれば
それを踏み台に Rubyist Connect の登録ユーザが増えるのでは？という考え方にも同意ですし
チャットサービスって、肌の合う人は使うし、そーでない人は使わないという感じかなと

現状、idobata よりも slack の方がプラットフォームを選ばずにクライアントソフトウェアが用意されていますし、idobata は「当面の間は無料です」って書かれてるのが少し気になったので slack で行こうかなと思いました。

その他、特にこだわりはないです。＃長々とすみません

**Comment by springaki** [comment]
> > 気軽にメッセージをやりとり出来る （荻さんの要望） 
> > できれば、Rubyist Connect 登録ユーザ全員にリーチしたい（寺田さんの要望）
> 
> slack / idobata どちらでも、上記の項目は満たせると考えています。（合ってます？）
> 
> > 気軽にメッセージをやりとり出来る （荻さんの要望）

の "気軽に" が測定不能なんですが メッセージのやり取りはできるので、これは満たせそう。
@t-oginogin idobata, slack, youroom のどれでも誘導できればこの要求は満たせますよね？

> > できれば、Rubyist Connect 登録ユーザ全員にリーチしたい（寺田さんの要望）

これは ユーザが全員明示的にチャットサービスにログインしないと不可能なので、本当に登録ユーザ全員にリーチしたいのであればどちらも達成できなさそう。

※ (Rubyist Connect 登録ユーザ全員にリーチしたい理由が書かれていればもうちょっと別の手を考えられそうです )
※※ (実は理由を知ってるからすごく意地悪な質問かもしれませんが、あの時の話を聞いているのは私と下田さんだけだったから、こういうOpenな場所では他の人にも意図が伝わるような方法で書くのが良さそう。たしかリクルーティングしたい的な内容でしたっけ？) ごめんね、めんどくさいこと書いてw :smile: 

(単純に slackに興味があるから使ってみたいというわけでなければ)
どういう趣旨でコミュニケーション取りたいのかによって結構ツールは変わりそうな気がします。
- どこまで無料プランなのか(rubyist connect ではなるべくコスト掛けない方針だと思うので)
- サービスログインの仕方(invite, 承認, guest access などどこまで必要？入りやすさはどこまで必要？)
- 運用コストはどこまで許容できるか？(承認に関係するところ...)
- (なぜ youroomではダメなのかとかを言葉にするだけでも本来の要求にたどり着く糸口になりそう)

とか...

潜在ユーザへのリーチとか開発巻き込みへの踏み台とか考えるのは、また別の話(別の要求) だと思うので、まず満たしたい事は何なのかなーと質問してみた次第です。

(と、いいつつ、別になんでもいいですよーと思っていたりはします :) )

**Comment by yuji-shimoda** [comment]
> どこまで無料プランなのか(rubyist connect ではなるべくコスト掛けない方針だと思うので)

はい、ご認識のとおりです。

> サービスログインの仕方(invite, 承認, guest access などどこまで必要？入りやすさはどこまで必要？)

どのサービスを利用しても、ここが一番面倒ですよね。
slack の invite を Rubyist Connect のサービス内にボタンを設けて、
クリックしたらメールが届くように出来たらいいなぁとか考えてました。
https://github.com/outsideris/slack-invite-automation

> 運用コストはどこまで許容できるか？(承認に関係するところ...)

できれば、全自動にしたいですよねー

> (なぜ youroomではダメなのかとかを言葉にするだけでも本来の要求にたどり着く糸口になりそう)

youroom でも全然良くて、ダメな理由は特にありませんね。

**Comment by JunichiIto** [comment]
Akiさんの話とかぶるかもしれないけど、そもそもRubyist Connectのユーザーで「他のメンバーと気軽にやりとりしたい」って考えている人がどれくらいいるのかなーと思いました。

少なくとも僕は一度も会ったことがない人にオンライン上でいきなりやりとりしようとは思わないですね。。。

もちろん「試験的にやってみる」というのであれば止める理由はないんですが。

ただ、Rubyist Connectのメンバー全員に「気軽にやりとりしてもらいたい」と思っているのであれば、なんとなくまだ時期尚早な気がしています。（僕らと全く面識のない人から機能リクエストが来たりしたらニーズがある証拠かもしれませんが）

**Comment by yuji-shimoda** [comment]
> できれば、Rubyist Connect 登録ユーザ全員にリーチしたい（寺田さんの要望）
> これは ユーザが全員明示的にチャットサービスにログインしないと不可能なので、本当に登録ユーザ全員にリーチしたいのであればどちらも達成できなさそう。

この意見は、一理ありですね。
各SNSアカウントすら登録していない人が、
チャットルームに join するとは思えませんし。
ひとまず、Twitter や Facebook ページもあるので知らない人から
何かしらの要望が届くようなサービスに成長してから考えた方が
現実的かもしれません。

＃一旦、再クローズでもいいかな
