### ISSUE TITLE
QiitaアイコンをGitHubに公開する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#187]
公開時は以下の記載を付ける。

”Qiita、Qiita:Team等のロゴをご利用希望の際はsupport@qiita.com までお問い合わせください。”

で、フォントアイコンをgemにして公開、ってどうやるんだろ？
そもそもgemだとRubyの人しか使えないのでベストではないかも。

このあたり、いい配布方式をご存知の方がいたら教えてください。

**Comment by kanizmb** [comment]
gemにこだわらないのであれば、普通にフォントとして配布でしょうか...？
ライセンス周りは私もよくわかりません〜。

2013年上半期 無料ダウンロード利用出来るwebアイコンフォントまとめ http://programmerbox.com/2013-07-18_free_web_icon_font/

**Comment by kanizmb** [comment]
アイコン化しましたー。
以下関連ファイルがまとまったzipファイルです。
https://www.dropbox.com/s/3cil3m73j2mgxm1/qiita_icon.zip?dl=0

一応こういう設定しておきました。
![qiita_icon_setting](https://cloud.githubusercontent.com/assets/4459676/5736731/a9fc4a0c-9c1c-11e4-946a-08bf7c427df3.png)

**Comment by JunichiIto** [comment]
@kanizmb ありがとうございます！
zipファイルの内容をこのまんま新しいGitHubリポジトリにpushして公開すればそれでいい気がしてきました。
GitHubならzipダウンロード用のリンクも付いてますし。

あと、READMEとかを編集したいな～と思ったときも、pull req送れますしね。

お時間のあるときにやってみてください～。

**Comment by kanizmb** [comment]
> zipファイルの内容をこのまんま新しいGitHubリポジトリにpushして公開

承知しました。
ファイルの場所は、 /public/downloads/qiita_icon_font/ 辺りでOKでしょうか？

**Comment by JunichiIto** [comment]
ん？認識がちょっと違うかも。
rubyist-connectとは完全に独立させて、 @kanizmbさんのリポジトリで公開するイメージでした。
たとえばこんな感じ。（"web font open source github" というキーワードでググりました）

https://github.com/aristath/elusive-iconfont

https://github.com/iconic/open-iconic

https://github.com/FortAwesome/Font-Awesome

Bowerとかに対応させると完璧っぽいです。（Bower、使ったことないですが）

**Comment by kanizmb** [comment]
なるほど！そういうことでしたか。
RubyistConnectのどこに置いてリンク貼るのだろう... と悩んでしまいました :sweat: 

公開のお作法がよくわかっていないので、ちょっと調べてみて対応しますね！
Bowerも合わせて見てみます〜 :dash:  いろいろありがとうございます。

**Comment by yuji-shimoda** [comment]
そういえば、ライセンスは MIT にしていたんですが Qiita icon ライセンスとのデュアルライセンスにしないといけない？

**Comment by kanizmb** [comment]
ブランドアイコンを含むfont awesomeのライセンスはこういう感じになっていますね。
http://fortawesome.github.io/Font-Awesome/license/

> - All brand icons are trademarks of their respective owners.
> - The use of these trademarks does not indicate endorsement of the trademark holder by Font Awesome, nor vice versa.

**Comment by yuji-shimoda** [comment]
こんな感じ？

Qiita アイコンおよび商標は、[Increments株式会社](http://increments.co.jp/)の著作物です。
Increments株式会社の許諾なく、Qiita アイコンを使用することはできません。

**Comment by yuji-shimoda** [comment]
[マイクロソフトの著作物の使用について](http://www.microsoft.com/ja-jp/mscorp/legal/permission/default.aspx) が、参考になるかも

**Comment by JunichiIto** [comment]
@yuji-shimoda Qiitaの中の人からはとりあえず「Qiita、Qiita:Team等のロゴをご利用希望の際はsupport@qiita.com までお問い合わせください。」と書いておいて、と言われています。
現在はQiita内で「規約の策定を準備中」らしいです。

ちなみにメールの全文は @kanizmb に転送してあります。

**Comment by yuji-shimoda** [comment]
rubyist-connect リポジトリのREADME(License)に、上記の１文を入れておけば良いでしょうか？

**Comment by kanizmb** [comment]
> ちなみにメールの全文は @kanizmb に転送してあります。

これ届いていない模様ですー @JunichiIto

**Comment by JunichiIto** [comment]
@kanizmb aiファイルを送ったメールに書いてある「ライセンス等について」の項を指しています。

**Comment by kanizmb** [comment]
@JunichiIto なるほどです！

**Comment by kanizmb** [comment]
いろいろ考えてみたのですが、この件私は実質アイコンサイトでの変換しかやっていないので、このアイコン配布はrubyist-connect名義でやるのが適当だと思います。
お手数ですがどなたかこのorgでの公開をお願いします〜。

**Comment by yuji-shimoda** [comment]
すっかり忘れていましたが、そろそろ着手しないといけませんね。
rubyist-connect 名義で、Qiita-icon リポジトリを作れば良いのでしょうか？

**Comment by JunichiIto** [comment]
@yuji-shimoda はい、そんな感じにしましょうかね～。ちなみにリポジトリ名は全部小文字の方が良い気がします。（慣習的に）

**Comment by yuji-shimoda** [comment]
@JunichiIto qiita-icon にします？

**Comment by JunichiIto** [comment]
@yuji-shimoda はい、それでいいと思います。

**Comment by yuji-shimoda** [comment]
https://github.com/rubyist-connect/qiita-icon リポジトリを作成し、zip ファイルの中身を commit しました。問題あれば、ご指摘ください。

**Comment by JunichiIto** [comment]
@yuji-shimoda ありがとうございます！いったんこのissueはクローズしておきます～。
