### ISSUE TITLE
ヘッダメニューにある"Rubyist Connect"もトップページと同じフォントにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#191]
ついでに beta も小さく入れたい。

**Comment by Koichi-Kobayashi** [comment]
ログイン直後のヘッダメニューだけっぽいんですけど、
イベントとかの右上のアイコンにマウスを乗せたら、
"Rubyist Connect”の文字が細くなるんですけど。。。
イベントの一覧画面では太いままです。

**Comment by JunichiIto** [comment]
@Koichi-Kobayashi 再現方法がわからなかったので、スクリーンショット付きで教えてください。

**Comment by Koichi-Kobayashi** [comment]
![2015-02-08 13 50 09](https://cloud.githubusercontent.com/assets/2451210/6095313/90fb581e-af99-11e4-9d84-ce5ce7946a6a.png)
↑
ログイン直後

**Comment by Koichi-Kobayashi** [comment]
![2015-02-08 13 50 44](https://cloud.githubusercontent.com/assets/2451210/6095318/d4f1e45c-af99-11e4-94c3-1dde1e030f46.png)

↑
ログイン直後の画面でマウスを右上のアイコンに乗せた瞬間
吹き出しが出るログイン直後画面のみだけ細くなります。
（イベント一覧に行って、ホームのアイコンで戻ってくるともう吹き出しも出ないという・・・別issueかなー。）

再現するブラウザ：Safari、Sleipnir
再現しないブラウザ；Chrome、Firefox

**Comment by Koichi-Kobayashi** [comment]
右上のアイコンの吹き出しがログイン直後しか出ない件は、
吹き出しが綺麗な吹き出しじゃなくなっているという意味です。
再現するブラウザ：Safari、Sleipnir、Chrome、Firefox

![2015-02-08 13 58 26](https://cloud.githubusercontent.com/assets/2451210/6095338/9f6a1c22-af9a-11e4-87e2-db972236a398.png)

**Comment by Koichi-Kobayashi** [comment]
あ、キャプチャ撮れなかった・・・

**Comment by Koichi-Kobayashi** [comment]
アイコンの吹き出しの件は #144 で対応とのことですが、
トップ（ログイン直後）のみだったのかな？

**Comment by hilohiro** [comment]
再現しました。トップページ以外でもリロードするとJSで作られた黒い背景のツールチップが出ますが、ページ遷移すると表示されずブラウザの普通のツールチップが表示されます。

**Comment by Koichi-Kobayashi** [comment]
おお！リロードすればイケてるツールチップになったｗ

**Comment by hilohiro** [comment]
リンク遷移したときはtooltip()の設定コードが呼び出されてませんね。
turbolinksとかが悪さしてるんでしょうか。

**Comment by hilohiro** [comment]
これっぽいですね。
http://stackoverflow.com/questions/18760842/twitter-bootstrap-tooltip-popover-display-issues
