### ISSUE TITLE
gitterのチャットをプライベートにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#192]
別にpublicでも害は無いだろうけど、外から丸見えなのもちょっと恥ずかしい。（ガラス張りの家に住んでる感じ）

プライベートモードみたいなものがあればプライベートにして、招待した人だけが参加できる、みたいな形にしたい。

そんなことできるんでしょうか？ > @springaki

**Comment by springaki** [comment]
できたハズです。 org にしたらやりましょうか。

**Comment by JunichiIto** [comment]
:+1: 
お願いしますー。

**Comment by springaki** [comment]
あ。これプライベートリポジトリでもない限り無理かも。

**Comment by yuji-shimoda** [comment]
無理なら無理で仕方ないですねー :sweat: クローズにします？

**Comment by JunichiIto** [comment]
これという代替案もないのでいったんクローズします－。
