### ISSUE TITLE
旧URLへのリクエストを新URLへリダイレクトする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#193]
これを使ってセットアップする。

https://github.com/SonicGarden/rack_redirectorr

**Comment by yuji-shimoda** [comment]
サブドメインもルートドメインも CNAME で転送できるみたいですよ！

**Comment by springaki** [comment]
SonicGarden製 !! 
これはなんですか？使わないとリダイレクトできないもの？

**Comment by JunichiIto** [comment]
現状リダイレクトできてますね。
CloudFlareの設定のおかげかな？

対応不要と言うことでクローズしますね。

**Comment by yuji-shimoda** [comment]
はい、CloudFlare のページルールで 301 redirect が出来るらしいので設定してから寝ました :+1: 
https://support.cloudflare.com/hc/en-us/articles/200172286-How-do-I-do-url-forwarding-with-CloudFlare-

**Comment by springaki** [comment]
あれ CloudFlare 使ってるんでしたっけ？

**Comment by yuji-shimoda** [comment]
ルートドメインへの移行に伴い、DNS を CloudFlare に変更しました :+1:

**Comment by springaki** [comment]
あ、そうなんですね。伊藤さんが知ってるって事はどこかでその発言をしてたって事か。
見逃してました。すみません〜 ><

**Comment by yuji-shimoda** [comment]
#179 で伊藤さんから無料だと教えて貰いました :+1:

**Comment by springaki** [comment]
なるほどなるほど。情報にたどり着きました。ありがとうございます !! :sparkles:
