### ISSUE TITLE
Heroku schedulerの設定、不要なら削除する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#195]
@yuji-shimoda 
`curl http://kobe.rubyist.co/`を1時間おきに実行していますが、これはHerokuが眠らないようにするためのスケジューラですか？

もしそうであれば現在はNew Relicがpingを飛ばしてるのでこのスケジューラは不要になります。

**Comment by yuji-shimoda** [comment]
はい、そうですー。削除しておきます :+1:

**Comment by yuji-shimoda** [comment]
削除しておきましたー :+1:
