### ISSUE TITLE
トップページでユーザーのアイコンをクリックすると認証ページへ飛ぶようにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#196]
「あ、このユーザー、どんな人だろう？気になる～」 
=> リンクをクリック => 認証ページ表示 => 認証
=> そのユーザーの詳細ページが開く

・・・という流れが理想。

**Comment by yuji-shimoda** [comment]
確かに、トップページのユーザアイコンからGitHub認証を経て
詳細ページにリダイレクトして欲しいですね。

**Comment by youcune** [comment]
`user_omniauth_authorize_path(:github, test: 'AAA')`

で渡したパラメータを Callback 後、以下で受け取れます。

`request.env['omniauth.params']`

参考
http://stackoverflow.com/questions/6657727/devise-omniauth-how-to-pass-extra-parameters-along
