### ISSUE TITLE
GitHub issueをもっと使いやすくする（ZenHub導入？）

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#198]
https://github.com/rubyist-connect/rubyist-connect/issues/86

の続きです。

GitHub issueをPivotalのように使いやすくする[ZenHub](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd)っていうChrome extensionがあるみたいですね。

http://qiita.com/sotayamashita/items/2cc6a32a0994b5069c7e

http://blog.isao.co.jp/post/87265630773/github-issue-zenhub

http://d.hatena.ne.jp/takezoe/20140607#p1

導入してみたらいいんじゃないかなーと思ったんですが、使ったことある人はいますか？

**Comment by springaki** [comment]
使った事あります。

問題は何を使うかよりは何を解決したいのかですねー。このレベルで issue上がってくるとツラいし、そういうのは gitterとかのコミュニケーションツールで揉んで欲しいなぁという感じ。

あとは issueで featureやstoryを管理するのかどうか。

**Comment by yuji-shimoda** [comment]
zenhub 入れてみました。issue の状態って、以下の４つだと考えているのですが
- 課題(New Issue)
- やること(TO DO)
- 作業中(Work In Progress)
- 完了(Done)

backlog って何ですか？

**Comment by t-oginogin** [comment]
zenhubはorganizationリポジトリは有料になったかも。（βのときは無料だったんですけどね）
30日間はお試しで使えるので使ってみて良いですね。

**Comment by yuji-shimoda** [comment]
おお、有償サービスですかー。残念、、、

**Comment by springaki** [comment]
おぉ、そうなんだ知らなかった...

**Comment by yuji-shimoda** [comment]
https://www.zenhub.io/pricing 　無料なのはあくまでも、個人利用っぽい感じですね

**Comment by yuji-shimoda** [comment]
https://trello.com/ 使います？

**Comment by yuji-shimoda** [comment]
とりあえず、現状維持で。この issue はクローズしておきますー
