### ISSUE TITLE
ユーザー一覧ページのアイコンサイズを、もうすこし小さくしたい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#200]
#176 で話題になった件です。

**Comment by kanizmb** [comment]
一覧ページのデザイン系issueが分散していますが、#148 に集約してはどうでしょうか？
（ユーザーのために）一覧性をUPするという目的に向かって進めば、どうするのが良いか明確になってくると思います！ :blush:

**Comment by JunichiIto** [comment]
そうしましょうか。
じゃあいったんこっちはクローズしますね。
