### ISSUE TITLE
Facebookページを作り直す

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#201]
@yuji-shimoda 
https://www.facebook.com/Rubyist.Connect のドットが気になるので https://www.facebook.com/RubyistConnect の方がいいです。

URLを変更するのは回数制限があった気がするので（名前だったかな？）、このタイミングであれば旧ページを削除して新しいページを作った方がいいかなと思います。

**Comment by yuji-shimoda** [comment]
![2015-01-17 9 58 32](https://cloud.githubusercontent.com/assets/2437500/5786830/823ded6c-9e2f-11e4-810f-8a89f6dd25d2.png)

アカウント作り直したんですが、ドットなしは無理そうですー

**Comment by springaki** [comment]
おや？試しに今やってみたら作れたよ。使いますか？

**Comment by springaki** [comment]
ちなみにURL変更の回数制限は1回だったはずですー

**Comment by yuji-shimoda** [comment]
使いたいです！

**Comment by springaki** [comment]
inviteしました。

**Comment by yuji-shimoda** [comment]
ありがとうございます！

**Comment by JunichiIto** [comment]
Thank you! 僕もinviteして～。

**Comment by springaki** [comment]
したよ〜。

**Comment by JunichiIto** [comment]
@springaki Thanks!
