### ISSUE TITLE
TOPページの説明を良くしたい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#203]
ハッカソン当日に時間の余裕もあまりない中、作成したため改善の余地あり

**Comment by yuji-shimoda** [comment]
![2015-01-17 10 56 59](https://cloud.githubusercontent.com/assets/2437500/5787176/7d7019d2-9e38-11e4-86bc-d3c772abdad1.png)
例えば、こんな感じ

**Comment by yuji-shimoda** [comment]
![2015-01-17 6 08 41](https://cloud.githubusercontent.com/assets/2437500/5788358/1f7bd3c0-9e74-11e4-9880-5ec6eb3941c0.png)

国際化対応

**Comment by yuji-shimoda** [comment]
@kanizmb 今のテキストより、英語版の方が良い気がしているのですが
問題無ければ修正しても良いですか？

**Comment by kanizmb** [comment]
@yuji-shimoda 
issueタイトルの「TOPページの説明を良く」は、「もっとユーザーにとってわかりやすく」だと思ったのですが違いますか？
このパーツは、未登録のユーザーにこのサイトが何のためにあるかの概要を素早く理解してもらうためにあります。当面のターゲットは日本人とのことでしたが、今回の変更でその機能が損なわれていないでしょうか。

文章を変更するのは賛成ですが、今の段階でここだけ英語にするのは方向が違うかな〜と思います :sweat_drops:

**Comment by yuji-shimoda** [comment]
そうですねー、もともとはもっと良い言い回しにしたいという issue でした。
英語版の方がシンプルだったんですが、それを和訳してアップデートの方向で
行こうかなと思いました。いかがでしょうか？

**Comment by kanizmb** [comment]
和訳した内容は何になりますか？

**Comment by yuji-shimoda** [comment]
- Search 近くの Rubyist を
- Share あなたのプロフィールを
- Support 勉強会を

ですかね

**Comment by kanizmb** [comment]
ひとまずOKかと思います〜。
入れてみたキャプチャをいただけますか？

**Comment by JunichiIto** [comment]
「xxのxxを」で並ぶと語呂がいいので「みんなの勉強会を」にしてみるのはどうでしょうか？

**Comment by yuji-shimoda** [comment]
伊藤さんの頂きます :+1:

**Comment by yuji-shimoda** [comment]
![2015-01-18 9 31 22](https://cloud.githubusercontent.com/assets/2437500/5790932/e42ab3e6-9ef4-11e4-9e44-cad289b4db98.png)

**Comment by kanizmb** [comment]
LGTMです:v:
テキスト修正だけなので、この内容で本番デプロイしてくださって構いません。

**Comment by yuji-shimoda** [comment]
クローズしますー
