### ISSUE TITLE
db:seedを使ってローカル開発環境に初期データを投入できるようにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#206]
[rake db:seedを使った初期データの投入](http://www.rubylife.jp/rails/model/index10.html)

サンプルデータがあった方がローカルでの動作確認もしやすそうなので。
Fakerを使ってそれっぽいデータを作るとさらによさそう。

このissueを思いついたきっかけはこちら。

https://github.com/rubyist-connect/rubyist-connect/pull/202#issuecomment-70350415

**Comment by kanizmb** [comment]
:sparkles:
