### ISSUE TITLE
ユーザー一覧で自分のデータは先頭に表示する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#208]
データ件数が多いと自分のデータが埋もれてしまう。
自分がどんなふうに見えているのかはすぐにチェックしたいのでは？

**Comment by yuji-shimoda** [comment]
#118 が解決策の予定なんですが、３カラムにして左側を自分のアカウント表示領域にしたいと考えていました。そうすれば、本来はユーザ一覧に自分のアカウントを表示する必要がなくなるはず

**Comment by kanizmb** [comment]
表示位置は先頭じゃないけどこれに準じたことやろうとしてました。

**Comment by JunichiIto** [comment]
ここにマージします。

https://github.com/rubyist-connect/rubyist-connect/issues/148
