### ISSUE TITLE
Kaminariのページャーに翻訳が当たっていない

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#213]
ネットを探せば日本語化の情報が見つかるはず。

![screen shot 2015-01-18 at 6 55 57](https://cloud.githubusercontent.com/assets/1148320/5790496/31f56032-9edf-11e4-8157-3b8581a0b0ff.png)

**Comment by yuji-shimoda** [comment]
本番環境にデプロイしておきました！
