### ISSUE TITLE
ユーザー名の吹き出しがかぶらないようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#215]
gitterではこれでひとまずOKということになっていましたが、個人的には気になるので、もう少し上下の間隔を広げたいです。

![screen shot 2015-01-18 at 7 59 14](https://cloud.githubusercontent.com/assets/1148320/5790685/11b027f4-9ee8-11e4-88e5-953326c18832.png)

**Comment by kanizmb** [comment]
上下をさらに空けるなら、あわせて左右も空けるほうが良いと思います。
吹き出しはあくまで補助機能なので、吹き出しが出ていない状態でバランスが取れていることを優先してください :dash:

**Comment by JunichiIto** [comment]
なるほど、その観点はありませんでした。
勉強になります！

**Comment by JunichiIto** [comment]
大きな問題ではないのでクローズ。
