### ISSUE TITLE
問い合わせ先のメールアドレスを用意する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#219]
利用規約とかに問い合わせ先を表示する必要があるため。
受け取り人はとりあえず下田さんってことでいいかな？
問い合わせが増えてきたらチームで管理する方法を検討するということで。

でも独自ドメイン + Google appsとかにしたらお金がかかるのな？
そういう話だとちょっと微妙かなー。

**Comment by JunichiIto** [comment]
まあ、最初はRubyistConnectの Twiiter IDとかでもいいのかなー。
いきなりお金かけてなくてもいい気がする。

**Comment by yuji-shimoda** [comment]
zoho.com で独自ドメインのメアド、10個まで無料らしいので
ひとまず info@rubyist.co は取得済みですー。support@rubyist.co を作成して
問い合わせ窓口用のアドレスに利用しようかと考えていました。
なお、info@rubyist.co は Twitter アカウントの取得用に使っており、
普段利用している gmail.com に転送設定しています。
＃現状、ドメイン利用料金以外は無料で済んでいますー :+1:

**Comment by yuji-shimoda** [comment]
support@rubyist.co は、info@rubyist.co の mail alias で作成しておきました。
また、gmail への転送をやめて iPad mini で info@rubyist.co から送受信できる環境設定を実施済みです。

問い合わせ窓口は、support@rubyist.co でお願いします。
ユーザ宛に何らかの通知が必要であれば、info@rubyist.co でメール送信します。
