### ISSUE TITLE
Event登録時のメンバー一覧に各個人のアイコンを表示する

### ISSUE THREAD

**Issue by t-oginogin** [rubyist-connect/rubyist-connect#221]
文字だけだと対象者を選びにくかったので

**Comment by yuji-shimoda** [comment]
アイコンあった方が探しやすくなる気がしますが、アルファベット順で綺麗に並べたり、地域を指定してリスト表示させる（不動産サイトのイメージ）などの工夫があれば、もう少し探しやすくなるのかなと思いました。

**Comment by JunichiIto** [comment]
対応済みなのでcloseします。
