### ISSUE TITLE
勉強会の時の昼食や懇親会の出欠予定も取れるといい

### ISSUE THREAD

**Issue by t-oginogin** [rubyist-connect/rubyist-connect#224]
1イベントと考えるとそれぞれ作っても良いです。
あるいはイベントにサブイベントを登録できるようにするのもあり？

**Comment by JunichiIto** [comment]
確かにあると便利そうですが、READMEにある「このアプリでやらないこと = 他のSNSサービスなどで代替出来る機能の提供」に該当しそうな気もしたりしなかったり。。。

あと、参加者全員がRCに登録してくれていることも前提条件になりますね。

**Comment by yuji-shimoda** [comment]
#62 で代替出来そうな気がします。
イベント運営側の作業負担を軽くするという目的であれば、参加者をカウントする機能があると便利ですね！＃例えば、昼食会？名、懇親会？名などなど

**Comment by t-oginogin** [comment]
#62で十分な気がするのでこちらはクローズしておきます。
集計機能はあってもよさそうですね。
