### ISSUE TITLE
イベントのユーザー一覧は、アイコンと名前のみにし見通しを良くしたい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#225]
勉強会での自己紹介時に利用するページなので、できれば一画面に収まるように変更した方が良いと感じた。詳細は、user#show で見るので

**Comment by JunichiIto** [comment]
https://github.com/rubyist-connect/rubyist-connect/issues/148 とかぶりそうですね。
別々のデザインを採用するのかどうか？？さしあたっては同じでも良さそうな気がしますが。

**Comment by yuji-shimoda** [comment]
#148 を実装してから、考えた方が良さそうですね。ひとまず、クローズしておきます。
