### ISSUE TITLE
ヘッダーアイコンに文言もつけたい

### ISSUE THREAD

**Issue by taiyop** [rubyist-connect/rubyist-connect#228]
見ただけで何をするアイコンなのかはっきりわからないから。

それぞれにホーム、イベント、設定、ログアウトの文言が欲しい

![image](https://cloud.githubusercontent.com/assets/1048048/6094802/8d3aa1d2-af7e-11e4-95a3-50a7d762659a.png)

**Comment by JunichiIto** [comment]
マウスオーバーで吹き出しが出るようになっているので、いったんクローズ。
