### ISSUE TITLE
User Searchで「_」(アンダースコア)が任意の一文字として扱われてしまう

### ISSUE THREAD

**Issue by tanaka-yoshi10** [rubyist-connect/rubyist-connect#229]
User Searchで「_」(アンダースコア)が任意の一文字として扱われてしまい、
意図した検索結果にならない。

SQLのLIKE文の中ではアンダースコアはワイルドカード(任意の一文字)として扱われる。
Ransackのbug?
あやしいのはここ
https://github.com/activerecord-hackery/ransack/blob/f4d7f6e0f547aae5f92f739214115dffb296926b/lib/ransack/adapters/active_record/ransack/constants.rb

```
        # Necessary for PostgreSQL and MySQL
        unescaped.to_s.gsub(/([\\|\%|.])/, '\\\\\\1')
```

**Comment by murajun1978** [comment]
issueを見返してみるとこんな感じでした
1. Non-SQLではアンダースコアをエスケープする必要ないでしょ！と言い出す
2. アンダースコアのエスケープ外す
3. いやいや、MySQLとPostgresSQLはいるでしょ
4. そして、アンダースコアを付け忘れたっぽい。。。

[#171 breaks searching for values with underscores](https://github.com/activerecord-hackery/ransack/issues/176)

**Comment by springaki** [comment]
@murajun1978 ありがとうございます。同じ所にたどり着きましたw

https://github.com/activerecord-hackery/ransack/releases/tag/v1.6.3 で直ってるハズなので `bundle update`して解決って事ですねー。

**Comment by yuji-shimoda** [comment]
この問題は、既に修正済みっぽい
