### ISSUE TITLE
ユーザー一覧の自己紹介はプレーンテキストで表示する + ある程度の長さで切る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#235]
- h1タグとかだと表示しきれない。
- 今はCSSでちょん切っているので、 Rails側で"..."とかにする => CSSで頑張ってもよいです

**Comment by hilohiro** [comment]
新しいデザインで2行になってましたがそれだとCSSで…にするのは難しそうです。
とりあえず手元で試して失敗しました。

**Comment by JunichiIto** [comment]
Duplicate https://github.com/rubyist-connect/rubyist-connect/issues/220
