### ISSUE TITLE
画面の幅が狭いときのデザインが考慮されていない

### ISSUE THREAD

**Issue by youcune** [rubyist-connect/rubyist-connect#236]
- 幅が狭いと、一番上のボタンが見えなくなります
- ページャーがプロフィールの右に回り込みます
  ![2015-02-08 14 15 29](https://cloud.githubusercontent.com/assets/2869221/6095370/2cac5b5c-af9d-11e4-9199-24ca176da4de.png)

**Comment by JunichiIto** [comment]
https://github.com/rubyist-connect/rubyist-connect/pull/226 => 「リキッドレイアウトに対応するか固定レイアウトに変更する」と同じ内容？

**Comment by youcune** [comment]
1点目については違います。
2点目についても @kanizmb さんの「リキッドレイアウトに対応するか固定レイアウトに変更する」を対応すると見た目上修正されるかもしれませんが、ページャーの要素に `clear` を入れておくべきだと思います。

**Comment by hilohiro** [comment]
1点目についてですが、実際には対応されているようで、ページの右上部分をクリックするとメニューが降りてきます。
[三]みたいなUIが用意されているのですが、色紙設定のため見えていないようです。

**Comment by hilohiro** [comment]
2点目については @youcune さんが仰る通り、`clear`を入れればいいと思います。
clearfixにするのとどっちがいいでしょう。今回だと直接`clear`でもいいようには思いますが。

**Comment by youcune** [comment]
:+1:
