### ISSUE TITLE
ユーザ一覧のユーザ表示を bootstrap card 表示にしたい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#248]
#226 でも言及されていましたが、丸アイコンの方が個人的には好みなので変更したいです。

**Comment by yuji-shimoda** [comment]
![2015-02-19 11 03 21](https://cloud.githubusercontent.com/assets/2437500/6267892/8a69ced6-b88b-11e4-8d39-31623d2544f3.png)

**Comment by yuji-shimoda** [comment]
イベントのユーザ一覧も、アイコンが四角になってますね。

**Comment by JunichiIto** [comment]
> イベントのユーザ一覧も、アイコンが四角になってますね。

イベントページはそもそもスタイルが崩れちゃってたような気が。

丸アイコンにするのはよいと思います！

**Comment by yuji-shimoda** [comment]
個人的には、users#index も events#index もユーザやイベントを以下のカード表示で
一覧するように変更したいと考えています。
https://v4-alpha.getbootstrap.com/components/card/

特に異論がなければ、issue のタイトル変更を考えていますー

**Comment by JunichiIto** [comment]
具体的にコレじゃないとダメ、というアイデアもないので、いったんカード表示で進めてみてもいいと思います。
ただ、実際にできあがったものを見て「あーだこーだ」言う可能性はありますがw

**Comment by yuji-shimoda** [comment]
デザインセンス無さ過ぎて辛いですが、イメージとしてはこんな感じです。
![2016-10-05 23 11 18](https://cloud.githubusercontent.com/assets/2437500/19116632/2c5fda3e-8b51-11e6-8284-6ff9f352def3.png)

ユーザは、そのままにイベントのみカード表示に変更する方が良いかも？

**Comment by JunichiIto** [comment]
ユーザーの顔写真の右横にスペースができるのがちょっと気になるかなー。
そもそもこの改善をしたいのはなぜなんだっけ？
現行のデザインと比べて何か特別良くなった気もしないんですが・・・。（失礼）

**Comment by yuji-shimoda** [comment]
当初は、アイコンを丸型に変更したいだけだったと思います。
で、bootstrap 4 のカードデザインを見たときに「このデザインでユーザ表示したら良さそう」と
思っただけですね。

> 現行のデザインと比べて何か特別良くなった気もしないんですが・・・。（失礼）

いや、むしろ今のデザインの方が良いなと思いました。 :sweat_drops: 

アイコンを丸く表示したいというリクエストも無いですし、クローズしたいと思います。

**Comment by JunichiIto** [comment]
とりあえず「やってみた」っていうことですね。
そのチャレンジ精神は 👍  です！

**Comment by yuji-shimoda** [comment]
> とりあえず「やってみた」っていうことですね。

仰るとおりです。
＃とにかく、やってみないと分かりませんもんね :+1:
