### ISSUE TITLE
登録しているユーザー数を表示したい

### ISSUE THREAD

**Issue by Koichi-Kobayashi** [rubyist-connect/rubyist-connect#249]
参考例
https://pplog.net/
このサイトの下の方にある犬の足跡みたいな画像に登録ユーザ数が表示されているイメージ。
画像はRubyのマークが良いとの意見。

**Comment by soruma** [comment]
@JunichiIto この issue は #376 と #369 で対応済みなので、クローズしても良いと思います。

**Comment by JunichiIto** [comment]
@soruma たしかに！closeします〜。
