### ISSUE TITLE
Herokuの新料金体系に対応する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#250]
正式発表はされていませんが、Herokuの料金設定が変わるようです。

http://www.octolabs.com/blogs/octoblog/2015/03/31/analysis-of-the-rumored-heroku-pricing-changes/

Free tier : Will be limited to 1 web dyno and 1 worker dyno, will sleep after 1 hour of inactivity, can be active for up to 12 hours a day, and can not support custom domains. Dynos have 512 MB RAM.

Free
- 使用できるのは1 web dynoと1 worker dynoまで
- 1時間動きがないとスリープする
- 1日で使用できるのは12時間まで
- 独自ドメインは使えない
- RAMは512MB

Hobby tier : Dynos can run 24x7 for $7/dyno/mo and custom domains are supported. Max of one dyno per Procfile entry. Dynos have 512 MB RAM.

Hobby
- $7/月（約840円）
- 毎日24時間使用できる
- 独自ドメインも使える
- Procfileごとに最大1dyno（合ってる？）
- RAMは512MB

---

独自ドメインを使っているので最低でも$7/月の出費が発生しそう。
うーん、どうするかな～。。。

**Comment by yuji-shimoda** [comment]
元々は、私の小遣いで賄えるような趣味のプロジェクトなので、
VPS などを検討したいと考えています。
＃コスパや条件的には、VPS の方が断然良さそうですね

**Comment by JunichiIto** [comment]
そうですね、VPS移行とかでもいいかもしれません。（VPSは使ったことがないのでよくわからないけど。。）

**Comment by yuji-shimoda** [comment]
公式のブログによると、Free Dyno は1日 18時間まで
カスタムドメインは、許可されているように見えます。
https://blog.heroku.com/archives/2015/5/7/heroku-free-dynos

現状維持でも問題は、無さそうですね。＃どうしようかな、、、

**Comment by JunichiIto** [comment]
問題を整理すると
- 現状 = 数秒おきにpingを飛ばしてdynoが眠らないようにしている
- 今は無料で済んでいるが新料金体系だと費用が発生してしまう
- 無料のままにしたいならpingを止める
- pingを止めると一定時間アクセスがないとdynoが眠る
- dynoが眠ると、時間を空けてアクセスされたときに10秒ぐらい待たされる（初回アクセスのみ）
- 体感的にはかなり遅いので「このサイト遅いな～。もういいや」って立ち去る人が出てきそう

という感じです。
とはいえ、今のサイトの運用状況ならpingを止めて初回アクセスの遅さを許容する、っていう判断でも良さそうな気がしますね。

**Comment by yuji-shimoda** [comment]
例えば、ping で Dyno プロセスを叩き起こすようにしている処理を、
AM 8:00 から AM 2:00 (18H) 程度に変更する（スケジューリング）ことは
出来ないでしょうか？

**Comment by yuji-shimoda** [comment]
現状、利用しているツール(サービス？)で無理ならば 
自宅で Raspberry Pi 動かして cron か何かで定期的に 
HTTP アクセスするようにすれば良いかな？と
安易に考えてました。

**Comment by yuji-shimoda** [comment]
以下の、New Relic の Pingers という機能でしょうか？
https://docs.newrelic.com/docs/alerts/alert-policies/downtime-alerts/availability-monitoring#pingers

**Comment by JunichiIto** [comment]
> New Relic の Pingers という機能でしょうか？

はい、そうです。

**Comment by JunichiIto** [comment]
> 現状、利用しているツール(サービス？)で無理ならば 自宅で Raspberry Pi 動かして cron か何かで定期的に HTTP アクセスするようにすれば良いかな？と安易に考えてました。

そうですね～、まあそうやってもいいとは思いますが、「時間を空けてアクセスされたときに10秒ぐらい待たされる（初回アクセスのみ）」っていう問題をどれくらい深刻に捉えるかに依りますね。

「ちょっと嫌だけど許容する」という判断をすれば、New Relicのpingを停止する、っていうアクションだけで終わります。

「許容できない」とか「個人的な趣味でRas Piを使ってみたい」というのであれば、やってみるのも手だとは思いますが。

ちなみに僕は許容してもいいかな～という考えです。

**Comment by yuji-shimoda** [comment]
> そうですね～、まあそうやってもいいとは思いますが、「時間を空けてアクセスされたときに10秒ぐらい待たされる（初回アクセスのみ）」っていう問題をどれくらい深刻に捉えるかに依りますね。
> 
> 現状のユーザ数や、アクセス状況を加味すると許容範囲かもしれませんね。
> VPS に移行するとなると、Deploy 手順も変わりますしコラボレーションも出来ないので
> 出来れば、当初の予定どおり heroku で運用したいと考えています。

**Comment by JunichiIto** [comment]
了解です。じゃあこの件は対応不要（pingだけ止める）っていうことで。
agreeならissueのcloseをお願いします。

新料金になったらpingを止めるアクションが必要ですね。（いつ始まるんだろう？）

**Comment by yuji-shimoda** [comment]
公式の Blog に記載のとおり、来月から適用されると思われます。
https://blog.heroku.com/archives/2015/5/7/new-dyno-types-public-beta
We believe these new dynos and pricing provide you a better set of choices when it comes to building and deploying apps. We plan to make these prices generally available next month, in June 2015. All new apps created as of that date will be on the new pricing.
＃忘れないように、今月中に ping は止めておきます。
