### ISSUE TITLE
イベントページで、ユーザをランダムに表示するボタンが欲しい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#254]
- 重複せずランダムに、ユーザを一巡表示する機能が欲しい（自己紹介の順番を考えるのが面倒）
- ボタンをクリックするだけで、次に自己紹介するユーザが表示される機能が欲しい（自己紹介時のブラウザ操作の負担を取り除きたい）

**Comment by JunichiIto** [comment]
二つ目の件はよくわかります。「次のユーザ」「前のユーザ」みたいなリンクがあれば良さそうですね。

一つ目の方はどうなんだろう。。。ランダムに、っていうところがこだわるポイントなのかどうか。

たとえば[テストコード相談会の参加者一覧](http://rubyist.co/nnect/events/3)であれば、ここで表示されている順番（伊藤、荻、otokunaga...Shimoda）に表示できればそれでいいのかなーと思ったりします。

**Comment by JunichiIto** [comment]
こんな感じでリンクを表示させてみました。

http://rubyist.co/nnect/events/3/users/yuji-shimoda

**Comment by yuji-shimoda** [comment]
> 二つ目の件はよくわかります。「次のユーザ」「前のユーザ」みたいなリンクがあれば良さそうですね。
> 
> 一つ目の方はどうなんだろう。。。ランダムに、っていうところがこだわるポイントなのかどうか。

対応ありがとうございました。
今日の勉強会で自己紹介が、凄くスムーズに流れていたのを観れて
自己紹介の進行をサポートする機能としての完成度は、身内で使う分には十分と思いました。

表示の順序が、ランダムでなくても機能的には困らないので一旦クローズにします。
＃毎回ランダムに順序表示され、固定されていない方が公平かなと思った次第
