### ISSUE TITLE
プロフィール編集時に退会ボタンが目立ちすぎる

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#262]
プロフィールを編集する際、退会ボタンがすぐ押せる場所にあって、更新ボタンが画面の下の方にあるので、間違って退会ボタンをクリックしそうになる。

**Comment by yuji-shimoda** [comment]
github の Danger Zone みたいに、間違ってリポジトリを削除することの無いような？
UIに変更した方が良いかもしれませんね。

**Comment by tanaka-yoshi10** [comment]
これでどうでしょうか。

## before

<img width="990" alt="2016-10-02 14 19 02" src="https://cloud.githubusercontent.com/assets/6820311/19018856/476e96ce-88ab-11e6-95f3-101fbb2e7c55.png">

## after

<img width="1067" alt="2016-10-02 14 47 19" src="https://cloud.githubusercontent.com/assets/6820311/19018957/2e3cfcf0-88af-11e6-8bec-954d4b912df6.png">
<img width="406" alt="2016-10-02 14 45 32" src="https://cloud.githubusercontent.com/assets/6820311/19018958/362a30d6-88af-11e6-85a4-34e0860276e6.png">

**Comment by tanaka-yoshi10** [comment]
字を薄くしました。

**Comment by JunichiIto** [comment]
Done! 🎉
