### ISSUE TITLE
イベント詳細画面に参加人数を表示する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#265]
Rubyist Connect上で何人の参加者がイベントページに登録されているか確認できると、過不足なく参加者を追加できているかどうか把握しやすい。

**Comment by springaki** [comment]
このチケットを "西脇.rb & 神戸.rb プログラミングキャンプ2019" で今からやりますー

**Comment by springaki** [comment]
released.
Thank you @rubyist-connect/camp2019-commiter team 😊

**Comment by soruma** [comment]
@JunichiIto @springaki すでに対応済みなので、クローズしても良いと思います。

<img width="660" alt="スクリーンショット 2020-05-26 19 03 23" src="https://user-images.githubusercontent.com/3359685/82888500-5a6fd780-9f84-11ea-93f2-6c7cc058ef05.png">

**Comment by JunichiIto** [comment]
ですね。Closeします。
報告ありがとうございます！！

**Comment by springaki** [comment]
@soruma ありがとうございます !! 😊
