### ISSUE TITLE
イベント一覧ページにデザインを適用する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#268]
イベント一覧のページは、少し味気ないので doorkeeper のイメージ画像を小さく表示したり見栄えを良くしたい。ユーザ一覧のページみたいに複数列で表示する感じ？（doorkeeper のサイトみたいな感じのイメージ）

**Comment by yuji-shimoda** [comment]
Bootstrap Cards のイメージです。
http://v4-alpha.getbootstrap.com/components/card/

こんな感じにしたい
https://gist.github.com/yuji-shimoda/d97c9552c2e9bc290f1f

**Comment by yuji-shimoda** [comment]
gist で、以下の定義が足りてませんでした。

``` css
.card-img-top {
  width: 100%;
  height: auto;
}
```

イメージは、こんな感じです。
![2016-01-07 0 14 57](https://cloud.githubusercontent.com/assets/2437500/12145829/c36db054-b4d3-11e5-8599-74d8b97c3586.png)

画像使い回してますが、イベント画像は doorkeeper api の /events/:id からevent.banner のリンクアドレスを GET する必要があります。

**Comment by yuji-shimoda** [comment]
あと、banner 画像が指定されてないイベントもあるみたいなので、ダミー用の画像を
用意しておいた方が良いかも？しれません

**Comment by yuji-shimoda** [comment]
![2016-10-07 1 35 20](https://cloud.githubusercontent.com/assets/2437500/19161364/77814614-8c2e-11e6-9b39-bf5ce9c5162c.png)

イメージは、こんな感じで考えているのですが CSS 難し過ぎて理解出来てません。
＃というか、リンクがクリック出来なくなってたりする

**Comment by JunichiIto** [comment]
この中にイベントの画像が表示されたら雰囲気が出そうですね。
細かいことをいうと、EditボタンとDeleteボタンが近すぎて押し間違いが発生しそう。
Deleteボタンは表示せずに編集画面にさりげなく配置するぐらいでいい気がする。
（ユーザー編集画面の削除リンクのように）

> イメージは、こんな感じで考えているのですが CSS 難し過ぎて理解出来てません。
> ＃というか、リンクがクリック出来なくなってたりする

これは勉強だと思って頑張って！！！

**Comment by yuji-shimoda** [comment]
> この中にイベントの画像が表示されたら雰囲気が出そうですね。

はい、イベントAPI でイベント画像の URL を取得したり、モデル側の
変更が必要だと考えてますが、画像が表示されていたら良い感じかな？と思いました。

> 細かいことをいうと、EditボタンとDeleteボタンが近すぎて押し間違いが発生しそう。
> Deleteボタンは表示せずに編集画面にさりげなく配置するぐらいでいい気がする。
> （ユーザー編集画面の削除リンクのように）

events#index 側には、編集と削除ボタンは不要かなと思ってます。
＃今は、card-footer 無しで画像のみの表示を試しているところ

> イメージは、こんな感じで考えているのですが CSS 難し過ぎて理解出来てません。
> ＃というか、リンクがクリック出来なくなってたりする
> これは勉強だと思って頑張って！！！

ですね、頑張るしかない :+1:

**Comment by yuji-shimoda** [comment]
![2016-10-08 0 56 41](https://cloud.githubusercontent.com/assets/2437500/19196900/42df5490-8cf2-11e6-8c91-26e9b4f98ed5.png)

こちらも作業中ですが、ユーザ一覧で適用されているスタイルをあててみました。
画像の表示サイズがカードスタイルに比べて小さくなりますが、サイト全体でのまとまりは
こちらの方が良さそうです。

**Comment by JunichiIto** [comment]
おお、基本路線としては悪くないですね。ユーザー一覧と一貫性も出ますし。
改善するとすれば、
- 編集と削除のボタンは不要（イベント詳細ページから編集ページに飛ぶ。イベントの削除もイベント編集ページから行うようにする）
- タイトルのリンクの文字色は赤だとちょっとうるさい（黒で表示して、hoverで赤くするとか？）
- 編集ボタン/削除ボタンの代わりに、DoorkeeperやConnpassへのリンクを表示するといいかも（設定されている場合）

みたいな感じでしょうか。
しかし、そもそもイベントの画像を取ってこないと、このレイアウトをリリースできないですね。。

**Comment by yuji-shimoda** [comment]
![スクリーンショット 2020-05-11 23 53 38](https://user-images.githubusercontent.com/2437500/81576082-c24dec00-93e2-11ea-977a-8bb2399884b6.png)

イベントの一覧ページにデザインを適用する前に、ユーザー一覧ページに 
Card デザインを適用しようと Try 中です。
（別 Issue で対応した方が良い気がしますが、一旦こちらでご意見いただきたく）

**Comment by JunichiIto** [comment]
@yuji-shimoda ぱっと見、良さそうですが、以下の2点が気になりました。

- 現在表示されている自己紹介文の一部がまったく表示されないので、どんな人なのかリンクをクリックしないと想像が付かない（以下は今のデザイン）

<img width="279" alt="Screen Shot 2020-05-12 at 9 04 21" src="https://user-images.githubusercontent.com/1148320/81623897-bccac300-942f-11ea-852e-87eb77b7a59b.png">

- 念のため、スマホ表示のレイアウトも見てみたい

**Comment by yuji-shimoda** [comment]
> 現在表示されている自己紹介文の一部がまったく表示されない

意図的に自己紹介文を表示させてなかったんですが、やっぱり一部表示しておいた方が良いですよね

> 念のため、スマホ表示のレイアウトも見てみたい

スマホ版でどう見えるかまでは、全く考慮してなかったです 😅

**Comment by yuji-shimoda** [comment]
https://getbootstrap.com/docs/4.0/components/card/
Card layout
> these layout options are not yet responsive.

レスポンシブ非対応らしいです、、、

**Comment by yuji-shimoda** [comment]
users.sass 側でウィンドウ幅に応じて、カラム数を可変にしたらうまくいきました
```sass
@media (min-width: 34em)
  .card-columns
    -webkit-column-count: 3
    -moz-column-count: 3
    column-count: 3

@media (min-width: 48em)
  .card-columns
    -webkit-column-count: 4
    -moz-column-count: 4
    column-count: 4

@media (min-width: 75em)
  .card-columns
    -webkit-column-count: 6
    -moz-column-count: 6
    column-count: 6
```
合わせて、自己紹介文も表示させて見ました。
![スクリーンショット 2020-05-13 0 55 55](https://user-images.githubusercontent.com/2437500/81716860-d4985a80-94b4-11ea-9f71-f70420133499.png)

**Comment by yuji-shimoda** [comment]
スマホ表示版です。
![スクリーンショット 2020-05-13 0 59 40](https://user-images.githubusercontent.com/2437500/81717061-0f9a8e00-94b5-11ea-870d-a5ff4d53279a.png)

**Comment by yuji-shimoda** [comment]
現状の実装では、Last Page でユーザー数が、24 より少ない場合
レイアウトが崩れる問題が発生していました。。。

**Comment by JunichiIto** [comment]
デザイン、よくなりました 🙆 

細かいところでいうと、以下の2点を調整してほしいです。（対応はいつでもOK）

- アイコン上下のマージンをもう少し取りたい＆同じ幅にしたい（赤線部分）
- 自己紹介の左右のマージンをもう少し取りたい（青線部分）

![81716860-d4985a80-94b4-11ea-9f71-f70420133499](https://user-images.githubusercontent.com/1148320/81770391-19ef7300-951b-11ea-81c4-f46226f77ad5.png)

**Comment by yuji-shimoda** [comment]
レビューありがとうございます！後日、時間見つけて確認します！
