### ISSUE TITLE
SendgridにSPFやDKIMの設定を追加する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#274]
迷惑メール扱いされる可能性を減らす。
おそらくDNSの関係の設定変更も必要。

**Comment by yuji-shimoda** [comment]
昨日、メール頂いた件はこの Issue でしょうか？

**Comment by JunichiIto** [comment]
そうです。クローズします。

**Comment by JunichiIto** [comment]
SendGridの表示が消えたことを確認しました。

![screen shot 2016-03-14 at 10 07 51](https://cloud.githubusercontent.com/assets/1148320/13732746/a9d85404-e9cc-11e5-895b-ca253cb74c2d.png)
　　↓
![screen shot 2016-03-14 at 10 06 43](https://cloud.githubusercontent.com/assets/1148320/13732749/b26799d6-e9cc-11e5-9d6e-6b6589c6586f.png)
