### ISSUE TITLE
ogタグがたぶんおかしい。意図しない画像が表示される

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#278]
確認の上、修正する。

![image](https://cloud.githubusercontent.com/assets/1148320/10129297/9307356e-65f7-11e5-9b53-d4d1fa525b48.png)

**Comment by soruma** [comment]
rubyist-connect には `og:image` は設定されていませんでした。
Twitter, Facebook で`og:image` あり・なしページへのリンクを貼り付けてみて検証した結果はこちらです。

| | Twitter | Facebook |
|--|--|--|
| `og:image` あり | og:image が表示される | og:image が表示される |
| `og:image` なし | イメージは表示されない | (おそらく)ページ配置されたイメージを選択できる |

この検証結果から、 `og:image` をページに設定すればこの問題は解決すると思われます。

@JunichiIto `og:image` には何を設定すれば良いでしょうか?
私の方で考えてみたのですが、これで良いでしょうか?

* トップページの場合
  * `touch-icon-iphone.png` と同様のイメージを設定
* ユーザーページの場合
  * ユーザーのアイコンを設定
* イベントページの場合
  * `og:image` に設定するイメージは、 Connpass, Doorkeeper それぞれのイベントページの `og:image` を rubyist.co の `og:image` に設定

**Comment by soruma** [comment]
OGP タグについて [Twitter card validator](https://cards-dev.twitter.com/validator) と [Facebook シェアデバッガー](https://developers.facebook.com/tools/debug) で検証してみました。
それぞれの SNS で同じように表示するには、 `og:image`, `og:title`, `og:description` を設定する必要があるようでした。
それに加えて Twitter では `twitter:card` も設定が必要でした。

## `og:image` を設定した場合

### Twitter

<img width="550" alt="Twitter-only-og-image" src="https://user-images.githubusercontent.com/3359685/80264186-3cd1f880-86ce-11ea-9bf2-e63a16e9e884.png">

### Facebook

<img width="553" alt="Facebook-only-og-image" src="https://user-images.githubusercontent.com/3359685/80264272-93d7cd80-86ce-11ea-8f34-184f4b6e1619.png">

## `og:image`, `og:title`, `og:description` を設定した場合

### Twitter

<img width="541" alt="Twitter-og-title-and-og-description" src="https://user-images.githubusercontent.com/3359685/80264194-4bb8ab00-86ce-11ea-9910-f12ca65dcc58.png">

#### Facebook

<img width="538" alt="Facebook-og-title-and-og-description" src="https://user-images.githubusercontent.com/3359685/80264204-5a9f5d80-86ce-11ea-901a-6194991e4db7.png">

**Comment by JunichiIto** [comment]
@soruma ご確認どうもありがとうございます！

og:imageは最低限、全ページでルビーのアイコンが出てくればOKです。

ユーザーのアイコンやイベントの画像は別ドメインからの取得になるので、Twitterでは表示されない可能性が高いです。（経験あり）

[Twitterカードの設定は正しいのに画像が表示されない原因 \| あぱーブログ](https://blog.apar.jp/web/9844/)

> 公式のアナウンスは見つけられませんでしたが、Twitterカードを設定している WebページのURLのドメイン名と、画像のURLのドメイン名が異なる場合は、Twitterカードに画像を表示しない仕様のようです。（2018年4月27日現在）
