### ISSUE TITLE
Doorkeeper API を認証付きAPI に移行する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#284]
https://www.doorkeeper.jp/news/2016/3/1/update-to-api
2016年5月31日以降に、認証無しAPI の提供が停止するかもしれない

**Comment by yuji-shimoda** [comment]
この issue 必要ないかも？と思い始めています。ひとまず、クローズします？

**Comment by JunichiIto** [comment]
> 最終的には認証なしAPIの提供を停止させて頂く予定です。
> 正確な日付は決まっていませんが、2016年5月31日以降を計画しています。

とあるので、いつか対応しないといけないと思ってる。
