### ISSUE TITLE
Let's Encrypt で SSL(TLS)導入

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#286]
以下の記事が参考になりそう
- [LET'S ENCRYPT WITH A RAILS APP ON HEROKU](http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/)

あとは、heroku の blog
- [Announcing Heroku Free SSL Beta and Flexible Dyno Hours](https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours)

**Comment by yuji-shimoda** [comment]
acme-challenge は成功した。

```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/rubyist.co/fullchain.pem. Your cert will
   expire on 2016-09-02. To obtain a new or tweaked version of this
   certificate in the future, simply run certbot again. To
   non-interactively renew *all* of your ceriticates, run "certbot
   renew"
```

しかし、Heroku での SSL 有効化は Hobby 以降の Dyno が必要（有料）

```
mba:rubyist-connect yuji$ sudo heroku _certs:add /etc/letsencrypt/live/rubyist.co/fullchain.pem /etc/letsencrypt/live/rubyist.co/privkey.pem --app rubyist-connect
Resolving trust chain... done
Adding SSL certificate to ⬢ rubyist-connect... !!!
 ▸    You need to be running on either Hobby or Professional dynos to be able to use SNI SSL.
mba:rubyist-connect yuji$
```

諦めた

**Comment by kntmrkm** [comment]
@yuji-shimoda 

http://apserver.hatenablog.com/entry/2015/11/29/004340

これなら無料でいけました。何か問題あるかもしれませんが。完全無料です。

http://kntmrkm.hatenablog.jp/entry/2016/06/05/224945

**Comment by yuji-shimoda** [comment]
@kntmrkm この設定だと、heroku 側の証明書がオレオレ証明書になってしまわないですか？

**Comment by kntmrkm** [comment]
@yuji-shimoda 
SSL詳しくはないのですが（書いておいてすみません）。
オレオレ証明書の動作とは違うようです。
http://qiita.com/Sheile/items/dc91128e8918fc823562

cloudflareの証明書で暗号化されるような設定になるようです。

個人のサービス公開レベルなら十分かもしれませんが、何か問題はあるかもしれませんね。

テストサイトはこんなかんじです。
https://test.orda.jp/

**Comment by yuji-shimoda** [comment]
書き方が悪かったですね。ごめんなさい。
heroku の web server とブラウザが通信する時は、heroku に登録した証明書が使われる筈ですが、その証明書はどこで認証して貰ってますか？

**Comment by kntmrkm** [comment]
恐らくこんな感じでしょうか。

Client（ブラウザ） <= Cloudflareの証明書 => Cloudflare <= Herokuappの証明書 => Heroku

PS 以下の記事によると香港経由のようです。
http://apserver.hatenablog.com/entry/2015/11/29/004340

**Comment by yuji-shimoda** [comment]
Heroku 側の証明書が利用されるんですねー。なるほど

**Comment by JunichiIto** [comment]
@yuji-shimoda 
現在進行形なのかもしれませんが、もしLet's Encryptの導入を諦めた場合はコードをrevertしておいてくださいね。
https://github.com/rubyist-connect/rubyist-connect/pull/289
https://github.com/rubyist-connect/rubyist-connect/pull/290

**Comment by yuji-shimoda** [comment]
Let's Encrypt 使いたければ、Heroku の Hobby プランに変更するか
VPS に移行するか AWS に移行するかどれかって感じですね。
どうしよう、、、

**Comment by JunichiIto** [comment]
そもそもRubyist ConnectをSSL対応する必要があるの？
興味本位かつお金は払いたくない、であれば、ここでクローズかな～。
Herokuから引っ越してまでやる必要があるのかな？って思いますね。

**Comment by yuji-shimoda** [comment]
もともとは、技術的な興味だけなのでクローズで

**Comment by yuji-shimoda** [comment]
CloudFront と AWS Certificate Manager 使って、HTTPS 対応しました。

**Comment by JunichiIto** [comment]
お疲れ様です！HTTPS化されているのを確認しました。

ただ僕からすると完全にブラックボックスというか、何をどうやってHTTPS化したのか見当が付かないので、どこかにやったことを簡単にまとめてもらえると嬉しいなーと思います。
よろしくお願いします。
