### ISSUE TITLE
イベント詳細ページのユーザ表示順序をランダムに変更する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#287]
毎回、自己紹介の順番がトップバッターで不公平感があるから

**Comment by springaki** [comment]
"西脇.rb & 神戸.rb プログラミングキャンプ2019" 用の暫定仕様

- リロードしても順番は変更されないこと
- 参加者を追加・削除したら順番をランダムにしなおす
- イベント自己紹介中に参加者が追加される事は今回は考慮しなくてよい

**Comment by JunichiIto** [comment]
設計案
![ios__________](https://user-images.githubusercontent.com/1148320/68552975-71bffb00-0460-11ea-96f8-08ae1c141acc.jpg)

**Comment by JunichiIto** [comment]
設計案へのフィードバックです。

- 削除のときは順番を入れ替える必要はないかも
- 参加者を追加した際に順番入れ替えだと利用者がビックリするかもしれないので、「順番シャッフルボタン」みたいなものを用意して、それがクリックされたタイミングでシャッフルするのもひとつの手かなー。
- 「イベント自己紹介中に参加者が追加されるたときは（というか、どのタイミングであれ参加者が追加されたら）一番最後に追加」という仕様にしておくと、新しく追加された人にも自己紹介の順番が回ってきそう
- orderカラムだとSQLやRailsの用語とかぶって混乱を招くので、名前はpositionの方がよさそう。
- null不許可、初期値0、ユニーク制約あり、だとmigrationを実行したときにユニーク制約違反が発生する（既存データが2件以上存在する場合）
- 既存のイベントの参加者の順番はどうなりますか？

**Comment by ml-okuda** [comment]
@JunichiIto 

レビューありがとうございます。

> null不許可、初期値0、ユニーク制約あり、だとmigrationを実行したときにユニーク制約違反が発生する（既存データが2件以上存在する場合）

こういう場合、どのように対応すべきでしょうか？
ユニーク制約を外して migration した後、データを適切に変更(postion にユニークな値を入れる)してから、ユニーク制約をかける migration を実行する、というように段階を踏むべきでしょうか。

**Comment by JunichiIto** [comment]
これ、僕が回答してもいいんだけど、せっかくなのでわいわいの他の3人の意見も聞いてみたいな〜。（ちょっと難しいかもしれないけど） > @rlho @rururu16 @kazuhi-ra

**Comment by springaki** [comment]
そうね〜。回答できるし、パッと思いつくとこうなるかな〜みたいなヤツはありそうですね〜。
自分達で編み出した"こうしなければならない"制約を作ってそうなので、元々どうしたかったんだっけ？に立ち返ってみるともっと簡単な方法思いつくかもよ？もっと楽な方法でやろう 😊 

せっかくだし、OSS 界隈でのやりとりではタイムゾーンの違う非同期コミュニケーションもよくあることなので、ここで議論できるならしてみてもよさそう〜

もしくは オンラインで集まって会話した結果をココに書いてくれるとかでもいいかもー :)

**Comment by JunichiIto** [comment]
ちょっと日が空いてきたので、僕からコメントしておきますね。

まず、今回の場合はpositionカラムにユニーク制約を付ける必要がそもそもあるかな？というところから考えた方がいいかもしれません。
もちろん、ユニークである方が望ましいですが、ユニークでないと人が死ぬ or 大金が失われる、というような致命的な問題は発生しません。（しょせん自己紹介の発表順だし！！）
また、`ORDER BY position, id` のようにしておけば、positionが重複した場合はid順にして並び順のユニーク性を保証することができます。
というわけで、ここは「Ruby側でなるべくユニーク性を担保するように努めるが、DB側にはあえて制約は付けない」とした方が費用対効果が高いのではないか、と僕は考えます。

もし仮にこの要件が「ユニークでないと人が死ぬ or 大金が失われる」というぐらい重要なものであれば、奥田さんが提案したような方法を採ることになると思います。

**Comment by ml-okuda** [comment]
間空いてしまいました、ありがとうございます！
確かに今回の場合であれば、必ずしもユニークでなくてもよさそうです！
