### ISSUE TITLE
ユーザ一覧ページから、自ユーザの表示をやめてページ上部に移動させる

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#294]
一覧出来るユーザ表示数が増えるため、視認性が上がるはず
![2016-09-15 0 31 45](https://cloud.githubusercontent.com/assets/2437500/18518751/4acae32c-7adc-11e6-8c06-2ae47b93a616.png)

**Comment by springaki** [comment]
LGTM 

動きも見てみたいので、[WIP] タイトルのPull Request 送ってくれるとコードも見れて手元でも確認できて便利です。

**Comment by yuji-shimoda** [comment]
まだ、VIEW 側しか変更しておらずロジック側を見直していないのですが
Work in Progress(作業中)のコードでも PR 送っていいよというコメントでしょうか？

**Comment by springaki** [comment]
あー。別にいいんじゃないですかねぇ。壊れてなければ。
その上でディスカッションしながら作っていく事はよくありますよ。

**Comment by yuji-shimoda** [comment]
![2016-09-16 11 16 07](https://cloud.githubusercontent.com/assets/2437500/18573518/1d7f8fb6-7bff-11e6-8b6d-497801b24eda.png)

個人的には、user#index ページでスクロールしたくないので１ページあたりの表示ユーザ数を
少なくし、スクロールしなくて良い感じにしたい

**Comment by JunichiIto** [comment]
クローズしますね。
