### ISSUE TITLE
イベントページから編集できるようにしたい

### ISSUE THREAD

**Issue by tanaka-yoshi10** [rubyist-connect/rubyist-connect#302]
現状、イベントの編集はイベント一覧からはできるが、
イベントページからはリンクがない。
(イベントページを見ててすぐに修正したい場合がある)

**Comment by springaki** [comment]
👍 
PRお待ちしております 😄

**Comment by tanaka-yoshi10** [comment]
タイトルの下に編集リンクをつけようと思います。

<img width="1181" alt="2016-10-01 15 02 50" src="https://cloud.githubusercontent.com/assets/6820311/19012170/63457548-87e8-11e6-88f5-3cf25e1be721.png">
<img width="421" alt="2016-10-01 15 03 10" src="https://cloud.githubusercontent.com/assets/6820311/19012169/6031a584-87e8-11e6-8ece-d025011fa59b.png">

本当はタイトル(h1)の右につけたかったのですが、
CSSの調整が必要そう(時間かかりそう)なので、まずは簡単なやり方にします。
参考)
http://bashalog.c-brains.jp/09/03/09-210351.php

**Comment by tanaka-yoshi10** [comment]
やっぱりタイトルの右横に編集へのリンクをつけました。

<img width="860" alt="big" src="https://cloud.githubusercontent.com/assets/6820311/19013788/2abe9df2-8816-11e6-9132-c1f42a62daa9.png">
<img width="395" alt="sm" src="https://cloud.githubusercontent.com/assets/6820311/19013789/2d050312-8816-11e6-9bba-96785a215f01.png">

**Comment by yuji-shimoda** [comment]
👍  ありがとうございましたー
