### ISSUE TITLE
app_scoped_user_idからFacebookアカウント名を割り出す

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#310]
Doorkeeper Sync / Connpass Syncでは以下のようなURLだとFacebookのアカウント名を取得できない

https://www.facebook.com/app_scoped_user_id/12345/

しかし、実際にこのリンクにアクセスするとリダイレクトしてURLからFBアカウント名を取得できるので、これもユーザー割り出しの手段にしたい。

**Comment by soruma** [comment]
Doorkeeper のプロフィールページに表示される Facebook リンクをクリックすると必ず「このコンテンツは現在ご利用いただけません」と表示される様になっていたので、 Doorkeeper サポートに問い合わせをすると

> 公開中のユーザープロフィールからFacebookアカウントプロフィールへのリンクを削除。Facebookアカウント経由でDoorkeeperにログインされた際、Doorkeeperに共有されるプロフィールリンクの動作が、2018年7月にFacebookにより変更されました。この変更により、当該リンクが安定して動作せず、無効となることが多く見受けられるようになりました。ユーザーの混乱を避けるため、Doorkeeperから当該リンクを完全に削除する決定をしました。

引用元: https://www.doorkeeper.jp/changelog

という様に、プロフィールページからFacebookリンクを削除する対応が取られた様です。
実際にプロフィールページからリンクが消えていました。

<img width="200" alt="Screen Shot 2020-05-11 at 23 50 20" src="https://user-images.githubusercontent.com/3359685/81575615-2fad4d00-93e2-11ea-84f8-5b6dcdaf4645.png">

**Comment by soruma** [comment]
connpass を確認すると Facebookの `app_scoped_user_id` が消えてしまっていました。

<img width="500" alt="Screen Shot 2020-05-11 at 23 51 43" src="https://user-images.githubusercontent.com/3359685/81575898-874bb880-93e2-11ea-8ace-5516e68573ec.png">

Facebook のリンクからユーザーを割り出すことができなくなっている様でした。

Rubyist Connect には Facebook のアカウントを登録してもらう機能は残しつつ、 Doorkeeper と connpass のFacebookからアカウントを割り出す機能を消した方がいいと思います。

**Comment by JunichiIto** [comment]
@soruma 

> Rubyist Connect には Facebook のアカウントを登録してもらう機能は残しつつ、 Doorkeeper と connpass のFacebookからアカウントを割り出す機能を消した方がいいと思います。

なるほど、このあたりはどんどん制約が厳しくなってきてますからね・・・。
細谷さんが提案してくれた対応でagreeです。
