### ISSUE TITLE
Connpass連携で存在しないURLを指定された場合を考慮する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#315]
http://x.connpass.com/event/38763/ を入力するとエラーになる。
（403を考慮していないため）

**Comment by soruma** [comment]
どのようなメッセージが良いでしょうか?
私は、`404` と同じ「イベントが見つかりません。URLを確認してください。」で良いかなと思っています。

**Comment by JunichiIto** [comment]
@soruma そうですね。特に違和感はないので、それで良いと思います。
