### ISSUE TITLE
ヘッダメニューの Home アイコンを廃止し、イベント作成ボタンに変更する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#317]
サイト名が同じ機能を提供しているため、不要な気がする。
また、イベント作成ページへのリンクがあった方が、便利な気がする。

カレンダーアイコンの tooltip を、ドロップダウンリストにして
一覧と作成のリンクを設ける方が直観的ではあるが（好みによるかも）

**Comment by JunichiIto** [comment]
確かにHomeアイコンはなくても支障がなさそうですね。

> カレンダーアイコンの tooltip を、ドロップダウンリストにして一覧と作成のリンクを設ける

これはその方がいい気がします。
でもHomeアイコン廃止とカレンダーアイコンの改善は別issueに分けた方がいいのでは。
