### ISSUE TITLE
Dockerのセットアップ方法をWikiに載せる

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#343]
https://github.com/rubyist-connect/rubyist-connect/pull/340

> マージ後 Wikiのアップデートもしましょうか。

とのことなので、アップデートお願いしたいです。（僕はDockerに関してはあまり詳しくない・・・）

**Comment by yuji-shimoda** [comment]
@JunichiIto Docker 版の環境構築手順（Wiki）作成しました！
- https://github.com/rubyist-connect/rubyist-connect/wiki/Procedure-for-setting-up-the-environment-when-using-Docker

検証確認して、Wiki の内容に問題がなければ Issue はクローズします。

**Comment by yuji-shimoda** [comment]
検証したところ、Action Controller で下記のエラーが発生しました。
Showing /app/app/views/layouts/top.html.slim where line #6 raised:
Autoprefixer doesn’t support Node v4.8.2. Update it.

コンテナ内の nodejs を確認したところ、確かにバージョンは v4.8.2 でした。
```
root@0e43dfea4ba0:/app# /usr/bin/nodejs -v
v4.8.2
```

下記の記事を参考に Dockerfile を修正したところ、対処できました。
- [Autoprefixer doesn’t support Node v4\.8\.2\. Update it \- Qiita](https://qiita.com/m-dove/items/a60b1a09d32299d215bb)

**Comment by JunichiIto** [comment]
ありがとうございます！僕もローカルで試してみました。

起動はうまくできましたが、docker-composeコマンドの使い方がいまいちわからなかったので、Wikiにリンクを追記しています。

https://github.com/rubyist-connect/rubyist-connect/wiki/Procedure-for-setting-up-the-environment-when-using-Docker

また、Wiki homeにもDocker版手順のリンクを追加しました。

https://github.com/rubyist-connect/rubyist-connect/wiki

というわけでこちらのissueはcloseしておきますね。
