### ISSUE TITLE
Heroku -> AWS へ移行したい

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#346]
学習を兼ねて AWS への移行を検討する。
現状のまま移行した場合、運用面での課題が残るため CD 環境を予め整えておく必要あり

**Comment by JunichiIto** [comment]
CD 環境って何の略？？

**Comment by yuji-shimoda** [comment]
> CD 環境って何の略？？

Continuous Deployment の略です！

**Comment by JunichiIto** [comment]
なるほど。であれば現行のHeroku環境もCDが実現できてるわけではないよね。

まあいずれにしても、AWSでさくっとデプロイできる仕組みがほしいのはたしか。
