### ISSUE TITLE
Net::ReadTimeout with #<TCPSocket:(closed)> がCIで発生したりしなかったりします

### ISSUE THREAD

**Issue by soruma** [rubyist-connect/rubyist-connect#360]
[Travis CI のエラー内容](https://travis-ci.org/github/rubyist-connect/rubyist-connect/builds/663959872?utm_source=github_status&utm_medium=notification)(CIは rebuild されているのでグリーンになっています。)

エラーの詳細
```
Failure/Error: visit user_github_omniauth_authorize_path

Net::ReadTimeout:
  Net::ReadTimeout with #<TCPSocket:(closed)>
# ./spec/support/login_macros.rb:38:in `sign_in_with_github'
# ./spec/support/login_macros.rb:11:in `sign_in_as_active_user'
# ./spec/features/doorkeeper_sync_spec.rb:7:in `block (2 levels) in <top (required)>'
# ./spec/rails_helper.rb:85:in `block (2 levels) in <top (required)>'
```

これは、どのように修正すれば良いでしょうか?
私が考えてみた対応策は以下です。
どちらも試したわけではないので、本当に状況が改善するかはわからないです。

**wait_time を変更する**

```ruby
Capybara.configure do |capybara_config|
  capybara_config.default_max_wait_time = 10
end
```

**retry回数を増やす**

```ruby
config.around :each, :js do |example|
  example.run_with_retry retry: 2
end
```

**Comment by JunichiIto** [comment]
これ、発生頻度も高くないし、致命的な問題でもないので、根本原因がわかるまではいったん放置しようかなと思います。

devやtestのgemを最新にしたら解決しないかな〜とも思ったり。（あてずっぽう）

**Comment by soruma** [comment]
どのタイミングからかは分かりませんが、ここのところエラーが発生していないようですので、クローズします。

**Comment by JunichiIto** [comment]
そもそもGithub Actionsに移行したので状況が変わっている可能性もありますね。
クローズ、了解です！
