### ISSUE TITLE
イベント編集画面のユーザー検索は大文字小文字を無視したい

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#361]
イベント編集画面のユーザー検索は大文字小文字を区別するが、挙動として直感に反する。
大文字小文字を区別せずに検索してほしい。

![6Q4LizsDyE](https://user-images.githubusercontent.com/1148320/77125711-09c29680-6a8a-11ea-9f65-f689476e31a6.gif)

**Comment by JunichiIto** [comment]
@soruma すいません、ステージング環境で動作確認したらこの動きが気になりました。
これも対応してもらえると助かります！ 🙏

**Comment by soruma** [comment]
@JunichiIto このチケットやります。

**Comment by JunichiIto** [comment]
@soruma 対応ありがとうございました！ 本番リリース済みです。
