### ISSUE TITLE
Doorkeeper のイベント情報取得に失敗します

### ISSUE THREAD

**Issue by soruma** [rubyist-connect/rubyist-connect#363]
https://nishiwaki-koberb.doorkeeper.jp/events/94827 のイベントを作成すると「イベントが見つかりません。URLを確認してください。」になります(既に同イベントを作成済みなので、このエラーはおかしい)。
`participants` ページのDOMが変更されているようで、参加者の取得に失敗しているため、イベント自体の取得に失敗しています。

[ChangeLog](https://www.doorkeeper.jp/changelog) を確認するとおそらく `2019-08-17` の更新からDOMが変更されたと思われます。

**Comment by soruma** [comment]
軽く確認した限り

* `user-profile-details` ➡ `member-list`
* `user-name` ➡ `member-name`
* `user-social` > `a` ➡ ~~`member-list-item` > `a`~~ ユーザー詳細ページの `external-profile-link` > `a`

と変更する必要がありそうです。

**Comment by JunichiIto** [comment]
報告ありがとうございます！
なるほど・・・スクレイピングあるあるな不具合ですね。
VCRのカセットもアップデートしないと。
