### ISSUE TITLE
GitHub Actionsでテストを自動実行する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#378]
現状Travis CIがいちおう動いているが、GitHub Actionsも気になる。
（PRにCIの結果を自動的に表示させたい）

参考 [Rails \+ RSpec \+ postgresをGitHub Actionsで自動テスト \| このコードわからん](https://hai3.net/blog/rails-rspec-postgres-github-action/)

**Comment by soruma** [comment]
@JunichiIto GitHub Action の設定したことあるので、お手伝いできます!!

**Comment by JunichiIto** [comment]
@soruma おお、すばらしい！時間があるときに試してもらえると嬉しいです😄
