### ISSUE TITLE
ログのuser_id表示をuser_idであることを明示的に表示したい

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#390]
https://github.com/rubyist-connect/rubyist-connect/pull/388 の対応してuser_idが表示されるようになったが、`[9]`だけだと何を表しているのか分かりづらい。`[user_id=9]`のような表記にした方がわかりやすそう。

<img width="1525" alt="Screen Shot 2020-07-05 at 8 01 45" src="https://user-images.githubusercontent.com/1148320/86522261-30200c80-be96-11ea-9d37-c774af4a6d81.png">

**Comment by soruma** [comment]
未ログインの場合は、どのように表示すれば良いでしょうか?
`[user_id=]`で良いでしょうか? それとも、`[user_id=]`を出さない方が良いでしょうか?

行っていないと思いますが、ログ解析のことを考えると`[user_id=]`の方が良いかなと思います。

**Comment by JunichiIto** [comment]
@soruma 特にこだわりはないです。が、なんとなくですが、`[user_id=]`だと「あれ？バグってる？？」と思われるような気もするので、どちらかといえば何も出さないがいいかなーと思います。ログ解析のニーズは今のところないので考慮不要です〜。
