### ISSUE TITLE
Heroku無料プラン廃止に対応する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#414]
https://blog.heroku.com/next-chapter の要点まとめ↓

- 2022/10/26から1年以上活動のないアカウントとそのストレージを削除する
- 2022/11/28から無料プランの提供を停止し、無料Dynoと無料DBの稼働を停止していく
- 影響を受けるユーザーにはメールで通知する
- Dynoは7$/月〜、Postgresは9$/月〜、Redisは$15月〜

2022/11/28までに「お金を払う（16$/月）」「別のプラットフォームにお引っ越しする」「停止する」の判断が必要になりそう。

**Comment by JunichiIto** [comment]
@yuji-shimoda 下田さんの中では何か方針は決まってますか？vercel + supabase？（詳しく知らないけど）

https://twitter.com/yuji_shimoda/status/1563010504922017793

**Comment by yuji-shimoda** [comment]
@JunichiIto 

これまで、Rubyist Connect のサービス維持費としてはドメイン代（年間で 4000円弱）のみでした。
Heroku へ課金してサービス提供を維持しようとは考えていない状況です。
現状、rubyist.co ドメインは 2023/6/1 まで利用可能ではあります。

そのため、選択肢としては下記のいずれかを考えております。
- 別のプラットフォームにお引っ越しする
- 停止する

> vercel + supabase
こちらは、技術的な興味からサービスを維持する場合の代替手段として色々と触っておりまして
機能足らずですが、それっぽいのを作りかけの状態です。
https://www.rubyist.co/

もし、サービスを継続して開発するのであれば、たくさんのユーザーに対して
価値を提供しつつ利用してもらえるサービスにしたいと思いつつも、何もアイデアがありません。
（サービスの開発を始めた頃とは、プライベートの状況やモチベーションが変化したことも大きいのですが

これまで、沢山の方々に助力いただきながらサービスを維持しておりましたが
Heroku 無料プランの提供廃止と共にサービス停止でも良いかなと考えております。

**Comment by JunichiIto** [comment]
返信ありがとうございます！

vercel + supabaseの移行は技術的には面白そう、と思いつつも、じゃあ下田さんと一緒に開発・運用していく強いモチベーションがあるかどうかと言われると、僕もちょっと厳しい感じですね。。
僕の場合、コロナ禍の影響で西脇.rb＆神戸.rbの活動も事実上停止してしまい、rubyist-connectを利用することもなくなってしまった、という理由が大きいです。

> これまで、沢山の方々に助力いただきながらサービスを維持しておりましたが
Heroku 無料プランの提供廃止と共にサービス停止でも良いかなと考えております。

ですねー。残念ですが僕も同意見です。
将来的にまたrubyist-connectが必要になる状況が出てきたら、何らかの再稼働プランを考えるかもしれませんが、現時点の状況を考えるとサービス停止が一番妥当な気がしています。

### To このスレッドを読んだ他のみなさん

何かご意見・ご感想があればこのスレッドに返信してやってください 🙏 

### その他

ちなみに西脇.rb＆神戸.rbで利用していたyouRoomも今年の12月でサービスを停止します。

[youRoom サービス終了について \- youRoom ヘルプ](https://sites.google.com/a/youroom.in/youroom-faq-ja/close)

西脇.rb＆神戸.rbは2013年に活動を始めましたが、約10年たってコミュニティを取り巻く状況がいろいろ変わってきたな〜と感じる今日この頃です。

**Comment by yuji-shimoda** [comment]
> コロナ禍の影響で西脇.rb＆神戸.rbの活動も事実上停止してしまい、rubyist-connectを利用することもなくなってしまった

当初は勉強会で利用する前提の自己紹介タイム効率化を目的としたサービスだったので、
コロナの影響で勉強会の開催＆参加が難しい現状だと利用する機会が無いのは仕方がないですよねぇ。。。

**Comment by yuji-shimoda** [comment]
Rubyist Connect サービス停止の方針で問題なければ、Heroku の課金が発生しないように
早めに撤収作業を実施しても良いのではないかと考えております。
特に異論が無いようであれば、10月のどこかで諸々作業を進めようかと考えておりますがいかがでしょうか？

**Comment by JunichiIto** [comment]
Herokuから低コストプランが発表されていたので確認しましたが、結局$10/月ぐらいはかかってしまいますね。。

https://twitter.com/jnchito/status/1576452243607298049

ポケットマネーで払えない額ではないですが、アクティブに使われていないことを考えると10月中にクローズでもいいと思います。

**Comment by yuji-shimoda** [comment]
Rubyist Connect サービス終了について、アナウンスしておきました！
https://twitter.com/RubyistConnect/status/1578636802445180929?s=20&t=rz5thC-xF1nb986o6bEGNg

**Comment by yuji-shimoda** [comment]
下記の対応を実施済み

- Heroku addon 削除
- Heroku Production および Staging アプリを削除
- Heroku に登録済みのクレカ情報を削除
- Google Domains の DNS 設定を削除
- 関連する AWS リソース（CloudFront,ACM,Route53,S3バケット）を削除
- GitHub OAuth アプリ設定を削除
- rubyist-connect リポジトリの README.md を更新
-  rubyist-connect リポジトリの GitHub Action 設定を停止

サービスへアクセスできなくなっていることを確認済み。
対応完了済みのため、本件クローズとします！

ありがとうございました :bow:

**Comment by JunichiIto** [comment]
@yuji-shimoda  ご対応どうもありがとうございました！
Twitterの投稿も確認しました。いやあ、なんかちょっとセンチメンタルな気分になりますね・・・🥲

あと、もしよかったら、FBページの方も終了アナウンスしてもらえると嬉しいです🙏

https://www.facebook.com/RubyistConnect

あとこのリポジトリもアーカイブしちゃった方がいいかもしれません。

https://docs.github.com/ja/repositories/archiving-a-github-repository/archiving-repositories

お手数ですがよろしくお願いします。

**Comment by yuji-shimoda** [comment]
> FBページの方も終了アナウンス

アナウンスしました！
