### ISSUE TITLE
興味があることをタグ付けしたい

### ISSUE THREAD

**Issue by hilohiro** [rubyist-connect/rubyist-connect#5]
## 欲求
- 自分と同じ興味を持っている人を知りたい、アクセスしたい
- 自分と同じ興味を持っている人からアクセスして欲しい
## 仕様
- ユーザーは自分が興味があることを複数設定できる
- ユーザーは他の人が興味があることを表示できる
- ユーザーはある分野に興味がある人の一覧を表示できる

**Comment by JunichiIto** [comment]
タグ機能の仕様や使い方が不明確なのでいったんクローズします。
