### ISSUE TITLE
ハッカソンやハッカソン後の開発でGitHub issueをどのように活用するか？

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#53]
Pivotal Trackerでの運用フローなら大体わかるんですが、GitHub issueでタスク管理していくフローがよくわかりません。

「このタスクは僕がやります」「着手しました」「終わりました」

的な連絡はどうやってやるのが一般的なんでしょうか？

**Comment by springaki** [comment]
Assignee で Asign したら 「このタスクは僕がやります」「着手しました」
closeで「終わりました」みたいな感じでしょうか。

問題になりそうなのはストーリ&バグを含めた優先順位付けですね。github issueでは優先度はLabelを使って表せるんですが、優先順位は表しにくい感じです。

**Comment by JunichiIto** [comment]
なるほどAssigneeか。今その存在に気付きました。（普段使ってないもので）

優先順位はとりあえずハッカソン当日はその場のコミュニケーションで解決できますよね。
ハッカソン以後はしばらく様子見かな～。
ハッカソン当日にチケットが対処しきれなかったときは、「ハッカソンの続き」としてその日に優先順位を決められそう。
