### ISSUE TITLE
CIを導入したい

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#54]
複数人で開発すると「知らぬ間にデグレードしてた」ということが起きそうなのでCIを入れて、テストを自動的に回すようにしたいです。

が、僕はあまりCI周りには詳しくありません。

「いい感じにやっておきます」という人がいたら対応をお願いしたいです。

**Comment by springaki** [comment]
これはやっておこう。

**Comment by yuji-shimoda** [comment]
一応、TravisCI というサービスを使ってみようかなと考えているんですが、おすすめありますか？

**Comment by springaki** [comment]
TravisCIやCircleCIとか色々ありますが、public repositoryだし、とりあえずTravisCIでいいかなーと思ってます。

**Comment by springaki** [comment]
とりあえず設定ファイルはコミットしました。
ここでモニタリングできますー
https://travis-ci.org/yuji-shimoda/rubyist-connect

**Comment by yuji-shimoda** [comment]
ありがとうございます！

**Comment by JunichiIto** [comment]
@springaki 設定ありがとう！！CIいいっすね～。
テストがFailしたときにコミッタにメール通知したりできます？
Sign inして設定を探してみたけどよくわからなかった・・・。

**Comment by springaki** [comment]
できますよ。今は gitterに流すようにしています。
それで十分かなーと思っているので。どうだろう？ :smile:

**Comment by JunichiIto** [comment]
なるほど！それならとりあえずその運用で良さそうですね :smiley:
