### ISSUE TITLE
Pull requestは本家のmasterに直接マージしても良いのか？

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#55]
「直接masterにマージしても構わない」という意見と、「pull requestはdevelopmentブランチにいったんマージして、リリース前にdevelopment => masterにマージすべき」という意見（ワークフロー？）があるように思います。

メリットデメリットを比較して、「こっちがいいと思う」という意見があれば教えてください。

ちなみに社内では後者のフローを採用しています。
が、rubyist-connectでそこまで本格的なフローでやるべきかどうかは確信がありません。（やってみないとわからないか？）

**Comment by springaki** [comment]
masterにpull request方式がいいんじゃないでしょうか。

アプリケーションの性質がクリティカルなものであれば git flow方式による段階マージがオススメです。これは各段階でなんらかのチェック・動作確認などをしたい要求があるからです。masterにマージされるまでの各段階でエラーを検出できるメリットがある反面、手間はかかります。

アプリケーションの性質がクリティカルなものでない場合、masterにマージした後にエラーが見つかったらすぐに直せばいいじゃんってスタイルなので、リリース・デプロイが素早く行えるのと、git flowのようにマージの段階に応じた確認作業が発生しません。その分、git flowのように各段階でチェックが入るような事がないので pull request マージ = デプロイとなりエラー混入の可能性は各人の意識、レビュー体制に依存してしまう感じです。

現段階ではアプリケーションの性質がクリティカルなものでなく、かつチェック体制作ってシステマチックにするのは難しそうなので、エラーは素早く直そうぜのスタンスで masterにpull request方式でどうでしょうか？ユーザ数やcontributorが増えたりした場合には見直すという事で :smile:

**Comment by JunichiIto** [comment]
@springaki Akiさんの意見にagreeです！いったんこの件はクローズしますね。

**Comment by springaki** [comment]
はーい。ありがとうございます :+1:
