### ISSUE TITLE
利用規約を作成する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#56]
一般公開されるサービスなので利用規約があった方が良い気がする。
（が、まだそこまでいらない気もする。。。）

**Comment by yuji-shimoda** [comment]
最低限の利用規約は、必要かもしれませんね。
＃ひとまず、西脇.rb と 神戸.rb 以外でも利用されるようになったら考えようかな、、、

**Comment by JunichiIto** [comment]
買ってみました。

![h27-01-16 8 36 46](https://cloud.githubusercontent.com/assets/1148320/5769252/500bdc60-9d5c-11e4-99cf-5e2250c53ab0.jpg)

これから読みまーす。

**Comment by yuji-shimoda** [comment]
:+1:

**Comment by yuji-shimoda** [comment]
グローバル展開も視野に :sparkles: 笑

**Comment by JunichiIto** [comment]
@みんな 自分で利用規約作ったことある人はいますか？いたらヘルプ希望です。
本を読んだり、他のwebサービスの利用規約をチェックしたりしていますが、なかなか難しいな〜という感想です。
自分一人でやるよりも経験者の人を交えて作った方が効率や品質の面で得策な気がするので、協力者を募集する次第です。
よろしくお願いします！

**Comment by springaki** [comment]
I will join. :+1:

**Comment by JunichiIto** [comment]
@springaki @yuji-shimoda 手を挙げてくれてありがとう！！
話の内容的にオンラインのキャッチボールだと効率が悪そうなので、一回skypeミーティングか何か開きたいですね。
今週は東京出張があってちょっと忙しいので、来週のどこかで時間を取りたいと思います。

**Comment by JunichiIto** [comment]
[参考情報] Qiitaで利用停止になったユーザーさんがいるみたい。

http://blog.qiita.com/post/109162836004/qiita

> 結果的に弊社サービス利用規約に基づきユーザー資格の取消という重い判断をさせていただきました。

利用規約を作っておかないとこういうケースで困る、って買った本にも書いてありました。

**Comment by t-oginogin** [comment]
この本良さそうですね！
しかも電子版もKindle版もある！
http://www.amazon.co.jp/o/ASIN/B00K2RFJK2/gihyojp-22

**Comment by JunichiIto** [comment]
はい、いい本だと思います。
このあたりの知識がほとんどなかったので、どこを読んでも「へ～、そうだったのか」という感じでした。

ただ、これさえ読めばスラスラ利用規約が書けるのかというと、それはまた別問題。。。
プログラミングの勉強と同じで、自分の事例に当てはめてゼロからイチを生み出すのは本を読むだけでは難しいですね～。

**Comment by JunichiIto** [comment]
個人レベル（？）でやってそうなwebサービスの利用規約をいくつか集めてみました。
- http://photoll.jp/termshttp://photoll.jp/terms
- http://flyteam.jp/docs/terms
- http://saifu.me/terms
- http://www.shot-idea.com/terms
- http://matomeweb.net/rules.php
