### ISSUE TITLE
Google Analyticsを導入する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#57]
とりあえず、簡易的なアクセスカウンタみたいなノリで導入しておいた方がいい気がする。

下田さんのアカウントで作成して、コミッタ陣に権限付与、みたいな形式か？

**Comment by yuji-shimoda** [comment]
とりあえず、サービスに登録しました。トラッキング コードをページに貼り付けるように記載されていますが、トップページをトラッキングするんですか？

**Comment by JunichiIto** [comment]
Google Analytics(GA)は全ページに付けます。
なのでlayoutsファイルに付ける感じですね。

あと、ステージングと本番環境のそれぞれでコードを発行してください。
（ステージングは数値を見る目的ではなく、GAの動作確認用です）

**Comment by springaki** [comment]
このチケット組み込みまですべて引き受けましょうかー？

**Comment by yuji-shimoda** [comment]
Aki さん、ありがとうございます。本番環境用の設定は、サイトで登録済みなんですがステージング環境のが、まだ作成出来ていません。Google Analytics のサイトって、すごく分かりにくい。
これって、引き継いだりとか出来るんでしょうか？

**Comment by springaki** [comment]
@yuji-shimoda  すべてこちらで作って組み込んで、皆さんに見てもらえるように権限付けられますよー。

もしせっかく作ったし...って感じならアナリティクス設定=>ユーザ設定 でメールアドレスを追加してもらえれば共有できますー。

**Comment by yuji-shimoda** [comment]
なるほど、共有出来るんですね。Google Analytics のサイト分かりにくすぎるんで、お願いしてもいいですか？

**Comment by springaki** [comment]
@yuji-shimoda 了解ー
