### ISSUE TITLE
Faviconを作る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#58]
機能的なメリットはほとんどないが、Faviconやアイコンがあると雰囲気が出て愛着が沸きそう。

**Comment by yuji-shimoda** [comment]
あと、GitHub 連携時に私のアイコンが表示されるので、それも合わせて変更したいです。

**Comment by yuji-shimoda** [comment]
ググったら、http://iconifier.net/ というサイトがオススメらしいんですが
favicon とか作ったことが無いので、有識者の方にご教示頂きたいです。
