### ISSUE TITLE
contributor の一覧ページを作成する

### ISSUE THREAD

**Issue by yuji-shimoda** [rubyist-connect/rubyist-connect#60]
現状、トップページに Author として私の名前（@yuji_shimoda） が記載されているのですが
本番環境で動くコード（やデザインなど）コントリビューターの名前を表示するために
専用のページを作成したいです。

**Comment by yuji-shimoda** [comment]
TOPページの Author も yuji_shimoda -> rubyist-connect developers に要修正。

**Comment by yuji-shimoda** [comment]
この件、今後のメンテナンス・コストも考えるとハッカソンでコントリビュート出来なかった参加者に
細かい修正でも良いのでコミットして貰って、github のコントリビューターのページで済ませたいです。

**Comment by yuji-shimoda** [comment]
github のコントリビューターのページは、以下ですね。
https://github.com/rubyist-connect/rubyist-connect/graphs/contributors

ただ、サービスとしてユーザの目線で考えると必要の無いページではある :sweat_drops:

**Comment by JunichiIto** [comment]
個人的にはあまり必要性を感じないですね～。
クローズしちゃってもいいんじゃない？

**Comment by yuji-shimoda** [comment]
どうしても作成して欲しいという方がいれば、コメントくださいー。
特にコメント無ければクローズしておきますー。＃クローズ後もコメントできますが
