### ISSUE TITLE
メールアドレスを登録して、新しいメンバーの通知を受け取るようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#63]
メールアドレスを登録すると、「XXXさんがKobe Rubyist Connectに参加しました！」みたいな通知が来ると嬉しいかも。

**Comment by yuji-shimoda** [comment]
イメージとしては、info@rubyist.co みたいなメールアドレスから通知が送信される感じで合ってますか？

**Comment by yuji-shimoda** [comment]
heroku だと、sendgrid というサービスが主流なんでしょうか？

**Comment by JunichiIto** [comment]
> イメージとしては、info@rubyist.co みたいなメールアドレスから通知が送信される感じで合ってますか？

そうですね。noreplyとかでも良いです。

> heroku だと、sendgrid というサービスが主流なんでしょうか？

昔はSendgridを使ってましたが最近は高機能 + 無料枠も大きいMandrillを使ってます。

**Comment by JunichiIto** [comment]
今日の英語勉強会でこのissueを対応しようと思います。

仕様はこんな感じ。
- プロフィール編集
  - プロフィール編集ページにメールアドレス欄を追加
  - 「新しいRubyistが参加したらメール通知する」チェックボックスを追加
  - 通知するにチェックを付けたらメールアドレス必須
  - できれば
    - チェックを入れたらメールアドレス欄を表示
    - 見た目を整える
    - メールアドレスのフォーマットチェック
- メール通知
  - 送信条件：自己紹介未入力 => 入力
    - introduction.blank? => present?
  - 更新に成功したら希望者にメール通知
    - BCCで一斉通知？
    - 送信者は誰？ noreply@rubyist.co ?
    - 自分には送らない
  - できれば
    - 通知はユーザーごとに一度きり
      - フラグを持たせる？（できれば）
      - 既存ユーザーにもフラグを立てる（introductionありなら送信済みとする）
