### ISSUE TITLE
メンバーのソーシャルな活動を可視化する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#64]
たとえば参加メンバーの
- Twitterでの発言
- GitHub上のアクティビティ（コミットしたとかスターを付けたとか）
- Qiita上のアクティビティ（投稿したとかストックしたとか）

の最新5件とかを表示すると、「へ～、この人はこんなことやってるんだ」というパーソナリティがわかって面白いかも。
もちろん、表示するデータは誰でもアクセスできるパブリックな情報のみです。

**Comment by aq2bq** [comment]
身近なrubyistがどんな活動しているのか、どんな分野に対して興味があるのか、タイムラインでざっと見れたらわかりやすいのではと思いました。

具体的には、他のissueでも出ているDoorkeeperでのアクティビティ、
- Qiita,StackOverflowでのアクティビティ
- ブログのRSS
- GitHubでのPublic Activity
- SlideShare

などを時系列に表示しておけば、そのRubyistの最近の関心あることがあって、コミュニケーションが捗るのではと思いますがいかがでしょうか？

rubyist-connectのコンセプトから離れてなければいいのですが。

**Comment by yuji-shimoda** [comment]
Ruby に関する活動に限らず、興味関心事や最近の活動内容が見える化されるという事ですね。
個人的には、凄く良いアイデアと思います！
＃機能として実装するのは、すごく難しそうなイメージなんですが。
上記のようなサービスは、聞いたことが無いので実現すると結構すごいツールな気がする

**Comment by kanizmb** [comment]
去年サービス終了した iddy.jp がイメージに近いのかな、と思いました。
http://www.ariel-networks.com/blogs/tokuriki/cat36/cat37/iddy.html
http://internet.watch.impress.co.jp/cda/news/2007/03/09/15036.html
http://hyper-text.org/archives/2007/05/iddy_new_template.shtml

![image](https://cloud.githubusercontent.com/assets/4459676/5687333/dcab7ca2-988e-11e4-9527-1ad1b15ab924.png)
![image](https://cloud.githubusercontent.com/assets/4459676/5687301/b7c90ef4-988e-11e4-9127-37a3138e3d3b.png)
