### ISSUE TITLE
READMEをちゃんと書く

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#69]

**Comment by yuji-shimoda** [comment]
これは、（多分）私の仕事ですね。

**Comment by yuji-shimoda** [comment]
この issue は、一旦クローズしても良いでしょうか？

**Comment by JunichiIto** [comment]
まだちゃんと見てないけどOKです！
直したいところがあったらまた新しいissue上げます。

他のissueも同じ進め方でOKです。（言い出しっぺの返事が遅いときは自主的にclose、という形式）

**Comment by yuji-shimoda** [comment]
了解です
