### ISSUE TITLE
ライセンスを明記する

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#70]
誰かOSSのライセンスに詳しい人います？

**Comment by yuji-shimoda** [comment]
詳しくは無いですが、MIT ライセンスにしようかなと考えています。
http://ja.wikipedia.org/wiki/MIT_License

**Comment by yuji-shimoda** [comment]
特に問題無ければ、マージしたいと思います。
コメントあればお願いします。

**Comment by yuji-shimoda** [comment]
MITライセンスとして公開しました。クローズします。

**Comment by yuji-shimoda** [comment]
Qiita アイコンの取り扱いについて、記載する必要があるかも

**Comment by yuji-shimoda** [comment]
とりあえず、README の License Qiita ロゴに関する内容を追記しておきましたー。

**Comment by JunichiIto** [comment]
@yuji-shimoda アイコンのライセンスの話は、アイコン単体をGitHubで公開するときに付与する文言になります。
Rubyist Connectはすでに許諾をもらってアイコンを使っているサイト、っていうイメージ。

というわけでREADMEから該当箇所を削除させてもらいました。

**Comment by yuji-shimoda** [comment]
了解です。こちらは、利用者側だからライセンスに記載する必要なしなんですね！
