### ISSUE TITLE
このアプリの骨子を明確にしたい

### ISSUE THREAD

**Issue by kanizmb** [rubyist-connect/rubyist-connect#76]
このアプリの骨子を明確にして、それに肉づけする形で進めると
- アプリの方向がぶれない
- 作業の優先順位がつけやすい
- 画面上での優先度がつけやすい

などができて良さそうでは〜と思います:blush:

**Comment by kanizmb** [comment]
例えばこんな感じです。
思い付きで書いているのでピントがずれてたらすみません:bow:

## 骨子

### このアプリで目指すこと
- 神戸界隈のRubyistの交流
- 神戸界隈のRuby/Rails情報の集約

### 交流とは？
- メンバープロフィールの共有
- メンバーの動きを知る
- イベント情報の共有
  - イベント開催情報
  - イベントレポート
- 質問＆回答

## 肉付け

### プロフィール項目
- アイコン
- 名前
- 各種アカウントへのリンク（github, twitter, facebook...）
- 興味のある分野（現状のタグ機能 #5）
- リンク（ブログや自作アプリなど）
- 自己紹介文

### メンバーの動きとは
- 新規メンバー参加の通知
- 既存メンバーの更新通知（ソーシャル活動の可視化 #64）

### 共有するイベント情報
- 神戸界隈のRuby/Railsのイベント
  - イベント名
  - 開催日時
  - 開催場所
  - 締め切り
  - 募集人数
- イベントレポート（Wiki,ブログ...）
  - RubyConnect外で書かれたレポートの管理は？

### 質問＆回答
- イベントと紐付けるかどうか
- 既存のyouRoomとの共存は？

### メモ
- イベント情報取得実装例: [兵庫県 rails関連イベント](http://eventdots.jp/events/table/keyword:ruby/area:5/prefecture:28/from:2014-12-31/)
- [DoorKeeper API](http://www.doorkeeperhq.com/developer/api)
- [youRoom API](http://apidoc.youroom.in/)

**Comment by yuji-shimoda** [comment]
まず、このアプリのコンセプトは名前のとおり Rubyist を繋げることに重点を置いています。
西脇.rb と 神戸.rb のおかげで沢山の Rubyist に出逢えることが出来ましたが、まだまだ沢山の
Rubyist に出逢えていないと思うので。ソーシャルな活動は、Twitter や Facebook、youRoom を通じて
活動すれば良いと思うのですが、他の SNS サービスでは各個人が Rubyist であるかどうかを
決定付けるような情報になかなかリーチ出来ないので、そのニッチな需要を埋めれればと考えています。ただサービスである以上は、何らかの value が必要なので
まずは勉強会特化型のツールとしてサービスを育てたいなと考えています。
＃要は、自分たちの勉強会で便利なツールとして開発しよう！という感じです。

逆に、他の SNS サービスなどで代替出来る機能は、無理に自分たちで作らなくても
適材適所で使い分けて行けば良いかなぁと考えています。

なお、このサービスは西脇.rb と 神戸.rb もくもく会の開催前に
自己紹介を行うのですが youRoom の自己紹介を記載するスペースが少なかったことと
Twitter や Facebook、GitHub のアカウントを毎回書くのが辛かったという経緯があり
開発をスタートしました。なので、勉強会特化型のツールとして育てるのが方向性としては
正しいかなと考えています。
＃回答になっていなかったら、すみません、、、

**Comment by yuji-shimoda** [comment]
あと、kobe はサブドメインなので需要があれば
いずれは kobe を外して http://rubyist.co/ で運営出来ればなぁと考えています。

**Comment by kanizmb** [comment]
ご回答ありがとうございます！！神戸は仮のくくりなんですね。
以下に今ある機能、お答えいただいたコメント、既存のissueから私の理解をまとめました。
現状の内容として大きく間違っていなければ一旦このissueはcloseします。
もし違っていれば遠慮なくご指摘ください〜。

### このアプリが目指すこと
- Rubyistのリスト化
- 勉強会に便利な機能の提供

### このアプリでやらないこと
- 他のSNSサービスなどで代替出来る機能の提供

### ターゲット
- Rubyist
- 地域は問わず（神戸と限らない）

### 主な機能
- **Rubyistのリスト化**
  - プロフィール情報の集約 [#76](#issuecomment-68477653)
  - 直近のソーシャル活動が見える #64
  - 登録済みユーザの検索, 閲覧 #13 #59
  - 新着ユーザの通知 #63 #72
- **タグ（興味のある分野）で繋がる**
  - "メタプロ" や "RSpec", "mruby" などで登録が出来、同じ分野に興味のある人がわかる #5 
  - タグでメンバーの絞り込みが出来る or タグごとにページがあり登録しているメンバーが見られる #5
  - お気に入りタグの管理 #34
- **勉強会情報の共有**
  - 開催予定の勉強会情報がわかる -> 参加者もわかる #73 
- **勉強会上のやりとりの補助**
  - 勉強会ごとにフリーページ（リスト, Wiki）を作れるようにする #44 #62

**Comment by yuji-shimoda** [comment]
@kanizmb 取りまとめ、ありがとうございました。README.md に内容を反映させ更新しました。

**Comment by kanizmb** [comment]
@yuji-shimoda @springaki 
マージありがとうございます！
具体的な機能については個別のissueで進めれば良いかなと思いますので、こちらは一旦closeします〜。
