### ISSUE TITLE
自己紹介未入力であればログイン後にプロフィール編集画面を表示する（アラート付きで）

### ISSUE THREAD

**Issue by ymoto** [rubyist-connect/rubyist-connect#79]
初めてログインした際に、ユーザ情報をどうやって登録（更新？）したらよいのかわからず、しばらく迷いました。

初めてログインした直後はユーザ情報を更新する画面に誘導するとか、ユーザ情報登録のボタン？を分かりやすくするとかして、ユーザ情報登録の画面にたどり着きやすくなればよいなと思います。

**Comment by yuji-shimoda** [comment]
確かに、現状のデザインだと分かりにくいかも
ロジック側で対処するのか、デザイン側で対処するのか
方法は色々あるかと思いますが、もう少し分かり易い
インターフェースにしないとダメですね。

**Comment by JunichiIto** [comment]
- 自己紹介欄が空白の場合、ログイン直後にプロフィール編集画面を表示する
  - その際、以下のような文言をalert表示する
  - 「あなたの自己紹介を入力すると、ユーザー一覧にあなたが表示されます」
  - 「この編集画面は画面右上のギアアイコン（ここにアイコンを入れる）からいつでも開くことができます」

みたいな仕様にするのはどうでしょう？

**Comment by JunichiIto** [comment]
https://github.com/yuji-shimoda/rubyist-connect/pull/142

で、「自己紹介欄が空白の場合、ログイン直後にプロフィール編集画面を表示する」は実装されましたが、アラートの表示はまだ実装されていません。

「なんでこの画面なの？？どうしたらいいの？？」ということになってしまうので、早めに説明を入れたい。
