### ISSUE TITLE
ログイン不要で閲覧だけ出来てもいいんじゃない？

### ISSUE THREAD

**Issue by Koichi-Kobayashi** [rubyist-connect/rubyist-connect#80]

**Comment by yuji-shimoda** [comment]
（賛否両論あるかもしれませんが）Rubyist 同士を繋げるためのサービスなので
ログイン無しの閲覧機能は、不要な気がします。
＃ログイン無しで閲覧されても connect 出来ないので
一応、退会機能は実装済みなのでログインを前提としたサービスで良い気がしますが
いかがでしょうか？

**Comment by Koichi-Kobayashi** [comment]
#76 のコメントにも書かれているように、
西脇.rb ＆ 神戸.rb の勉強会前にyouRoomで自己紹介を書く際の
面倒な事を省くという事を主としているのであれば、ログイン前提で良い気がしました。

Rubyist を繋げることに重点を置くという観点では、
ログインしないとどんなサービスか分からないので、
ログインしなくてもどんな事が出来るサービスか分かれば良いと思いました。

**Comment by yuji-shimoda** [comment]
多分、サイト（サービス）に関する説明が抜けているというご指摘ですね。
＃つまり、 About ページが必要と理解しました。

認識に齟齬が無ければ、新しくissue を作成します。こちらはクローズで良いでしょうか？

**Comment by Koichi-Kobayashi** [comment]
その認識で相違ないです。
