### ISSUE TITLE
ユーザー詳細ページに活動タイムラインをつける

### ISSUE THREAD

**Issue by aq2bq** [rubyist-connect/rubyist-connect#82]
身近なrubyistがどんな活動しているのか、どんな分野に対して興味があるのか、タイムラインでざっと見れたらわかりやすいのではと思いました。

具体的には、他のissueでも出ているDoorkeeperでのアクティビティ、
- Qiita,StackOverflowでのアクティビティ
- ブログのRSS
- GitHubでのPublic Activity

などを時系列に表示しておけば、そのRubyistの最近の関心あることがあって、コミュニケーションが捗るのではと思いますがいかがでしょうか？  
rubyist-connectのコンセプトから離れてなければいいのですが。

**Comment by aq2bq** [comment]
#64 を見逃していて、かぶっていました。。とりあえず補足ということで。

**Comment by springaki** [comment]
@aq2bq  duplicated なので #64に同じ内容をコメントしていただいた後、閉じていただけると助かります !!
