### ISSUE TITLE
自分の興味のある技術分野を登録したり、他のメンバーが興味を持っている技術分野を検索できるようにする

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#86]

**Comment by JunichiIto** [comment]
タグ機能、やりたいことがまだふわっとしているので、もしやるならもう少し具体的なユースケースや仕様に固めたいです。

参考：タグ絡みの別issue

https://github.com/yuji-shimoda/rubyist-connect/issues/5

**Comment by yuji-shimoda** [comment]
タグ機能は削除されたので、一旦クローズしませんか？

**Comment by JunichiIto** [comment]
この案自体は寺田さんから出たものです。
クローズするとなかったことになるので備忘録的に置いておこうかな～と思っています。
とりあえず紛らわしいので「タグ機能」という言葉を使わないタイトルにしました。

※GitHub issueは優先度や仕様が固まっているのかどうかを表現しづらいのが難点ですね。
仕様が決まっててすぐに対応できるものを上に集めたりしたいな～。

**Comment by yuji-shimoda** [comment]
了解ですー。そこは、Milestone で対応？

**Comment by JunichiIto** [comment]
うーん、issueには3つぐらい状態があるのかなーと思っています。
1. 優先度の高い機能。早く対応してほしい。
2. 仕様は固まっているが、なくてもそこまで困らない機能。「なるはや」で対応されると嬉しい。
3. 要件がまだふわっとしているので着手できない。まずは目的や仕様を固めるところから。

Milestoneが該当するのは1かなー。
2はたくさんあるのでいちいちマイルストーンを付けていくのは大変。
で、このissueは3に該当する感じ。

ちなみにPivotal Trackerだとドラッグアンドドロップで移動して、3カラムで表現できるから理想的なんですが。

![pivotal](http://depth-first.com/images/posts/chemwriter-tracker.png)

1,2はcurrentかbacklogに入って、3はiceboxに入る。
2の中でも「現時点では対応不要」みたいなものはiceboxに入る。
3でも「早急に検討が必要」ならcurrentやbacklogに入る。

**Comment by yuji-shimoda** [comment]
おー、こんなツールがあるんですね :+1: 便利そう

**Comment by JunichiIto** [comment]
便利なんだけど、有料なんですよね。。。

**Comment by springaki** [comment]
正直 GitHub issue は issueとしてだけ使いたいような気もしますね。そんなに feature上がってこないと予測してこのままにしてたんですが、そろそろ厳しいですね。

Pivotalもいいんですが、高機能すぎ & 有料だからなぁ。
Trello でいいんじゃないですか？

**Comment by yuji-shimoda** [comment]
この件も、一旦凍結扱いで良いでしょうか？（issue 整理中）

**Comment by JunichiIto** [comment]
いいんじゃないかなー。
