### ISSUE TITLE
コミュニティでグループを作る

### ISSUE THREAD

**Issue by JunichiIto** [rubyist-connect/rubyist-connect#87]

**Comment by yuji-shimoda** [comment]
events#Index に、複数のコミュニティ・イベントが散見される状態なので
コミュニティ単位でグルーピングしたいなと思いました。#222 も同じようなリクエストかと

**Comment by JunichiIto** [comment]
このリクエストはDoorkeeper上のコミュニティ（西脇.rbとか新大阪.rb）をまとめるもので、 https://github.com/rubyist-connect/rubyist-connect/issues/222 はユーザーの属性をまとめるものなので、微妙に違う気もします。

いずれにしても、コミュニティの管理機能を付けたりするのは結構大変なので、イベントやユーザーに「タグ」を付けられるようにして、タグレベルで管理できるようになればいいのかな～とか思ったりもします。（雑な解決案）

**Comment by yuji-shimoda** [comment]
group モデルに、name/owner/url くらいのデータと
ユーザおよびイベントへのリレーションを持たせ
作成されたグループは、それを作成したオーナーにしか削除出来ない
程度の機能でも良いかな？とか雑に考えてました。

＃イメージとしては現状のイベントモデルに、has_many :events のリレーションと
＃イベントを作った人しか削除させない的な機能追加で
＃グループ単位でのイベント表示が可能(要件が満たせる)かなと考えてました。

**Comment by JunichiIto** [comment]
ん？このissueってイベントの削除権限を管理するものでしたっけ？

> ＃イベントを作った人しか削除させない的な機能追加で
> ＃グループ単位でのイベント表示が可能(要件が満たせる)かなと考えてました。

ここのつながりがちょっとよくわかりませんでした。
削除権限のコントロールとイベントのグルーピングがどうつながるのか？
イベントの作成者ごとにイベントをグルーピングするつもり？

**Comment by yuji-shimoda** [comment]
説明が下手で混乱させてしまいました、すみません。

何となくのイメージですが、グループをイベントとして作成してしまい
グループとして作成されたイベントが、複数のイベントを持てるように
変更すれば、グループ機能っぽいことが出来るのかなと考えてました。
1. イベントとしてグループを作成(イベント名にグループ名を指定して、グループ参加メンバを登録する)
2. グループとして登録されたイベントが複数のイベントを持てるように変更
3. グループとして登録されたイベントのみを一覧表示
4. グループとして登録されたイベントを event#show すると、過去のイベントが一覧表示される

ただし、グループとして登録されたイベントは削除されると困るので
グループとして登録されたイベントの作成者（オーナー）のみに削除権限を与える
という感じで考えてました。

普通に Group モデルを追加する方がいいですよね :sweat: 
グループのアイコンとか、そのグループを説明するための説明文章とか
色々と追加したい情報とかあるだろうし、、、

**Comment by yuji-shimoda** [comment]
そもそものリクエストとしては、作成されたイベントが、どのコミュニティの主催するイベントなのかをフィルタリングするための機能追加という理解で正しいですか？
上記の理解が正しいのならば、タグ機能を追加し、タグでフィルタリング出来るようにする方が
簡単なのかなーと思いました。

**Comment by JunichiIto** [comment]
> 普通に Group モデルを追加する方がいいですよね

はい、イベントが親子構造になるのはトリッキーだし、この場合はメリットがなさそうです。

> そもそものリクエストとしては、作成されたイベントが、どのコミュニティの主催するイベントなのかをフィルタリングするための機能追加という理解で正しいですか？

はっきり覚えてないんですが、AとCとDは西脇.rb＆神戸.rbのイベント、BとEは新大阪.rbのイベント、みたいに分けたかったんじゃないかなーと思います。
が、そもそも現状そこまでその機能を必要としていないので、今は真剣に設計する必要もないかなーという感じです。
