### ISSUE TITLE
GitHub API 用の画像を変更する

### ISSUE THREAD

**Issue by kanizmb** [rubyist-connect/rubyist-connect#96]
GitHub認証時に表示されるアイコンを添付ファイルに変更してください @yuji-shimoda 

![ruby_gem_illust02](https://cloud.githubusercontent.com/assets/4459676/5690245/cd718cfa-98bf-11e4-91c0-b6b445ecf635.png)

**Comment by yuji-shimoda** [comment]
GitHub アプリケーション側に、上記の画像を追加しました。クローズします。
