### ISSUE TITLE
ページ全体のデザインをかっこよくしたい

### ISSUE THREAD

**Issue by yamasy1549** [rubyist-connect/rubyist-connect#97]
今とってもBootstrapなので。
（navbar、button、paginationとか）

Bootstrapを使いながらもBootstrap臭をなくしたいです！！

**Comment by kanizmb** [comment]
トップページ案とロゴフォント（webフォント）案リストつくってみました
https://dl.dropboxusercontent.com/u/350306729/rubyistconnect_fonts.html

![image](https://cloud.githubusercontent.com/assets/4459676/5690369/c78b03ea-98c7-11e4-9d8d-b3151f06818d.png)

**Comment by kanizmb** [comment]
ユーザー一覧ページのワイヤフレームです
![image](https://cloud.githubusercontent.com/assets/4459676/5690439/c664f4ee-98cc-11e4-99d7-d6749470d303.png)

**Comment by JunichiIto** [comment]
@yamasy1549  @kanizmb 
https://github.com/yuji-shimoda/rubyist-connect/pull/115 と https://github.com/yuji-shimoda/rubyist-connect/pull/125 がマージされたので、いったんこのissueはクローズします。
残タスクがあれば新しいissueを作成してください。
